'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/utils/currency';

type PO={id:string;po_number:string;supplier_id:string;status:string;total_cost:number;suppliers?:{name:string}};
type POItem={id:string;product_id:string;supplier_product_name:string|null;supplier_sku:string|null;gtin:string|null;quantity_ordered:number;quantity_received:number;unit_cost:number;products?:{name:string;sku:string|null;gtin:string|null;image_url:string|null}};
type Scan={poItem:POItem;quantity:number;batch_id:string;expiry_date:string;invoice_unit_cost:string;notes:string};

export default function NewGRNClient(){
 const router=useRouter(),params=useSearchParams(),poParam=params.get('po');
 const [pos,setPOs]=useState<PO[]>([]),[po,setPO]=useState<PO|null>(null),[poItems,setPOItems]=useState<POItem[]>([]),[invoiceId,setInvoiceId]=useState('');
 const [invoiceNumber,setInvoiceNumber]=useState(''),[invoiceDate,setInvoiceDate]=useState(new Date().toISOString().slice(0,10)),[invoiceTotal,setInvoiceTotal]=useState(''),[invoiceTax,setInvoiceTax]=useState(''),[invoiceShipping,setInvoiceShipping]=useState(''),[invoiceFile,setInvoiceFile]=useState<File|null>(null);
 const [scan,setScan]=useState(''),[modal,setModal]=useState<Scan|null>(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);const inputRef=useRef<HTMLInputElement>(null);
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('purchase_orders').select('id,po_number,supplier_id,status,total_cost,suppliers(name)').in('status',['draft','sent','confirmed','partially_received']).order('created_at',{ascending:false});if(error)setError(error.message);const rows=(data||[]) as any;setPOs(rows);if(poParam){const found=rows.find((x:any)=>x.id===poParam);if(found)setPO(found);}setLoading(false)};
 useEffect(()=>{load()},[]);useEffect(()=>{if(!po)return;(async()=>{const {data,error}=await supabase.from('purchase_order_items').select('*,products(name,sku,gtin,image_url)').eq('purchase_order_id',po.id).order('created_at');if(error)setError(error.message);setPOItems((data||[]) as any)})()},[po]);
 const ensureInvoice=async()=>{if(invoiceId)return invoiceId;if(!po||!invoiceNumber.trim())throw new Error('Supplier invoice number is required');let fileUrl:string|null=null;if(invoiceFile){const path=`${po.supplier_id}/${Date.now()}-${invoiceFile.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const u=await supabase.storage.from('supplier-invoices').upload(path,invoiceFile,{upsert:false});if(u.error)throw u.error;fileUrl=path}const {data,error}=await supabase.from('supplier_invoices').insert({supplier_id:po.supplier_id,purchase_order_id:po.id,invoice_number:invoiceNumber.trim(),invoice_date:invoiceDate,total_amount:Number(invoiceTotal)||0,tax_amount:Number(invoiceTax)||0,shipping_cost:Number(invoiceShipping)||0,subtotal:0,currency:'GBP',status:'draft',file_url:fileUrl,invoice_file_name:invoiceFile?.name||null,uploaded_at:invoiceFile?new Date().toISOString():null}).select('id').single();if(error)throw error;setInvoiceId(data.id);return data.id};
 const handleScan=async()=>{const code=scan.trim();if(!code)return;if(!po){alert('Select a Purchase Order first.');return}const item=poItems.find(i=>i.products?.gtin===code||i.gtin===code);if(!item){alert(`GTIN ${code} is not on this Purchase Order.`);setScan('');return}const remaining=Math.max(item.quantity_ordered-item.quantity_received,0);if(!remaining){alert('This PO line is already fully received.');setScan('');return}setModal({poItem:item,quantity:1,batch_id:'',expiry_date:'',invoice_unit_cost:String(item.unit_cost||''),notes:''});setScan('')};
 const save=async()=>{if(!modal||!po)return;if(modal.quantity<1||!modal.expiry_date){alert('Quantity and expiry date are required.');return}setSaving(true);setError(null);try{const inv=await ensureInvoice();const {data,error}=await supabase.rpc('receive_purchase_scan_with_invoice',{p_purchase_order_id:po.id,p_supplier_invoice_id:inv,p_gtin:modal.poItem.products?.gtin||modal.poItem.gtin,p_quantity:modal.quantity,p_expiry_date:modal.expiry_date,p_batch_id:modal.batch_id||null,p_invoice_unit_cost:Number(modal.invoice_unit_cost)||modal.poItem.unit_cost,p_notes:modal.notes||null});if(error)throw error;setModal(null);const {data:items}=await supabase.from('purchase_order_items').select('*,products(name,sku,gtin,image_url)').eq('purchase_order_id',po.id).order('created_at');setPOItems((items||[]) as any)}catch(e:any){setError(e.message||'Failed to receive item.')}finally{setSaving(false);setTimeout(()=>inputRef.current?.focus(),50)}};
 if(loading)return <div className="p-10 text-center text-slate-500">Loading purchase receiving…</div>;
 const ordered=poItems.reduce((s,i)=>s+i.quantity_ordered,0),received=poItems.reduce((s,i)=>s+i.quantity_received,0),remaining=ordered-received;
 return <div className="p-6 max-w-[1600px] mx-auto space-y-6"><header className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><h1 className="text-2xl font-black text-white uppercase">Receive Purchase</h1><p className="text-sm text-slate-500">PO → invoice → GTIN scan → quantity + batch + expiry → inventory</p></div><button onClick={()=>router.push('/inventory-management/grn')} className="px-5 py-3 bg-slate-800 text-white rounded-xl font-bold">Back</button></header>{error&&<div className="p-4 rounded-2xl border border-rose-500/30 bg-rose-500/10 text-rose-300">{error}</div>}
 <div className="grid grid-cols-1 xl:grid-cols-3 gap-6"><section className="bg-slate-900/60 border border-slate-800 rounded-3xl p-6 space-y-5"><h2 className="text-xs font-black text-cyan-400 uppercase">Purchase Order</h2><select value={po?.id||''} onChange={e=>setPO(pos.find(x=>x.id===e.target.value)||null)} className="w-full bg-slate-800 border border-slate-700 rounded-xl px-4 py-3 text-white"><option value="">Select open PO…</option>{pos.map(x=><option key={x.id} value={x.id}>{x.po_number} · {x.suppliers?.name||'Supplier'} · {formatCurrency(x.total_cost)}</option>)}</select>{po&&<div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-500">Supplier</span><b className="text-white">{po.suppliers?.name}</b></div><div className="grid grid-cols-3 gap-2 pt-3"><div className="bg-slate-800/60 p-3 rounded-xl"><span className="text-[9px] text-slate-500 block">Ordered</span><b>{ordered}</b></div><div className="bg-slate-800/60 p-3 rounded-xl"><span className="text-[9px] text-slate-500 block">Received</span><b className="text-emerald-400">{received}</b></div><div className="bg-slate-800/60 p-3 rounded-xl"><span className="text-[9px] text-slate-500 block">Remaining</span><b className="text-amber-400">{remaining}</b></div></div></div>}</section>
 <section className="xl:col-span-2 bg-slate-900/60 border border-slate-800 rounded-3xl p-6 space-y-5"><h2 className="text-xs font-black text-cyan-400 uppercase">Supplier Invoice</h2><div className="grid grid-cols-1 md:grid-cols-5 gap-3"><input value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)} placeholder="Invoice number *" className="bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/><input type="date" value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)} className="bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/><input type="number" value={invoiceTotal} onChange={e=>setInvoiceTotal(e.target.value)} placeholder="Invoice total" className="bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/><input type="number" value={invoiceTax} onChange={e=>setInvoiceTax(e.target.value)} placeholder="VAT" className="bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/><label className="bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-400 cursor-pointer">Invoice file<input type="file" accept="application/pdf,image/*" onChange={e=>setInvoiceFile(e.target.files?.[0]||null)} className="hidden"/>{invoiceFile&&<span className="block text-emerald-400 truncate">{invoiceFile.name}</span>}</label></div><p className="text-[10px] text-slate-500">The invoice is linked to the selected PO and stored privately.</p></section></div>
 <section className="bg-slate-900/60 border border-cyan-500/20 rounded-3xl overflow-hidden"><div className="p-5 border-b border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h2 className="text-sm font-black text-white uppercase">GTIN Receiving Scanner</h2><p className="text-[10px] text-slate-500">Only products on the selected PO can be received.</p></div><form onSubmit={e=>{e.preventDefault();handleScan()}} className="flex gap-2"><input ref={inputRef} autoFocus value={scan} onChange={e=>setScan(e.target.value)} placeholder="Scan GTIN…" disabled={!po} className="w-72 bg-slate-800 border border-cyan-500/40 rounded-xl px-4 py-3 text-white font-mono outline-none"/><button className="px-5 py-3 bg-cyan-600 text-white rounded-xl font-black">SCAN</button></form></div><div className="divide-y divide-slate-800">{poItems.map(i=><div key={i.id} className="p-4 flex items-center justify-between gap-4"><div><b className="text-white">{i.products?.name||i.supplier_product_name}</b><div className="text-[10px] text-slate-500 font-mono">GTIN {i.products?.gtin||i.gtin||'—'} · SKU {i.supplier_sku||i.products?.sku||'—'}</div></div><div className="flex gap-6 text-xs"><span className="text-slate-500">PO <b className="text-white">{i.quantity_ordered}</b></span><span className="text-emerald-400">Received <b>{i.quantity_received}</b></span><span className="text-amber-400">Remaining <b>{Math.max(i.quantity_ordered-i.quantity_received,0)}</b></span></div></div>)}</div></section>
 {modal&&<div className="fixed inset-0 z-[100] bg-black/70 flex items-center justify-center p-4"><div className="w-full max-w-lg bg-slate-900 border border-slate-700 rounded-3xl p-6 shadow-2xl space-y-5"><div><p className="text-[10px] font-black text-cyan-400 uppercase">Product matched</p><h2 className="text-xl font-black text-white">{modal.poItem.products?.name||modal.poItem.supplier_product_name}</h2><p className="text-xs text-slate-500 font-mono">GTIN {modal.poItem.products?.gtin||modal.poItem.gtin} · PO remaining {Math.max(modal.poItem.quantity_ordered-modal.poItem.quantity_received,0)}</p></div><div className="grid grid-cols-2 gap-3"><label className="text-xs text-slate-400">Received quantity<input type="number" min={1} max={Math.max(modal.poItem.quantity_ordered-modal.poItem.quantity_received,1)} value={modal.quantity} onChange={e=>setModal({...modal,quantity:Number(e.target.value)||0})} className="mt-1 w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/></label><label className="text-xs text-slate-400">Expiry date *<input type="date" value={modal.expiry_date} onChange={e=>setModal({...modal,expiry_date:e.target.value})} className="mt-1 w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/></label><label className="text-xs text-slate-400">Batch / Lot<input value={modal.batch_id} onChange={e=>setModal({...modal,batch_id:e.target.value})} className="mt-1 w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/></label><label className="text-xs text-slate-400">Invoice unit cost<input type="number" step="0.0001" value={modal.invoice_unit_cost} onChange={e=>setModal({...modal,invoice_unit_cost:e.target.value})} className="mt-1 w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/></label></div><label className="text-xs text-slate-400">Notes<textarea value={modal.notes} onChange={e=>setModal({...modal,notes:e.target.value})} rows={2} className="mt-1 w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-3 text-white"/></label><div className="flex justify-end gap-3"><button onClick={()=>setModal(null)} className="px-5 py-3 bg-slate-800 text-slate-300 rounded-xl font-bold">Cancel</button><button onClick={save} disabled={saving} className="px-6 py-3 bg-emerald-600 text-white rounded-xl font-black">{saving?'Saving…':'Confirm Receipt'}</button></div></div></div>}
 </div>;
}
