'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {supabase} from '@/lib/supabase';
import {formatCurrency} from '@/lib/utils/currency';

type PO={id:string;po_number:string;supplier_id:string;status:string;total_cost:number;suppliers?:{name:string}};
type Item={id:string;product_id:string;gtin:string|null;supplier_sku?:string|null;quantity_ordered:number;quantity_received:number;unit_cost:number;supplier_product_name:string|null;products?:{name:string;sku:string|null;gtin:string|null;image_url:string|null}};
export default function WarehouseReceivingClient(){
 const router=useRouter(),q=useSearchParams(),poParam=q.get('po'),scanRef=useRef<HTMLInputElement>(null);
 const [pos,setPos]=useState<PO[]>([]),[po,setPo]=useState<PO|null>(null),[items,setItems]=useState<Item[]>([]),[code,setCode]=useState(''),[invoiceId,setInvoiceId]=useState(''),[invoiceNo,setInvoiceNo]=useState(''),[invoiceDate,setInvoiceDate]=useState(new Date().toISOString().slice(0,10)),[invoiceTotal,setInvoiceTotal]=useState(''),[vat,setVat]=useState(''),[shipping,setShipping]=useState(''),[file,setFile]=useState<File|null>(null),[modal,setModal]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 const loadPos=async()=>{const {data,error}=await supabase.from('purchase_orders').select('id,po_number,supplier_id,status,total_cost,suppliers(name)').in('status',['draft','sent','confirmed','partially_received']).order('created_at',{ascending:false});if(error)setError(error.message);const r=(data||[]) as any;setPos(r);if(poParam){const x=r.find((p:any)=>p.id===poParam);if(x)setPo(x)}};
 const loadItems=async(id:string)=>{const {data,error}=await supabase.from('purchase_order_items').select('*,products(name,sku,gtin,image_url)').eq('purchase_order_id',id).order('created_at');if(error)setError(error.message);setItems((data||[]) as any)};
 useEffect(()=>{loadPos()},[]);useEffect(()=>{if(po)loadItems(po.id)},[po]);
 const ensureInvoice=async()=>{if(invoiceId)return invoiceId;if(!po||!invoiceNo.trim())throw Error('Supplier invoice number is required before receiving.');let fileUrl=null;if(file){const path=`${po.supplier_id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const u=await supabase.storage.from('supplier-invoices').upload(path,file);if(u.error)throw u.error;fileUrl=path}const {data,error}=await supabase.from('supplier_invoices').insert({supplier_id:po.supplier_id,purchase_order_id:po.id,invoice_number:invoiceNo.trim(),invoice_date:invoiceDate,total_amount:Number(invoiceTotal)||0,tax_amount:Number(vat)||0,shipping_cost:Number(shipping)||0,subtotal:0,currency:'GBP',status:'draft',file_url:fileUrl,invoice_file_name:file?.name||null,uploaded_at:file?new Date().toISOString():null}).select('id').single();if(error)throw error;setInvoiceId(data.id);return data.id};
 const scan=()=>{setError('');setOk('');const c=code.trim();if(!po){setError('Select a purchase order first.');return}const item=items.find(i=>i.products?.gtin===c||i.gtin===c);if(!item){setError(`GTIN ${c} is not on ${po.po_number}.`);setCode('');return}const rem=Math.max(item.quantity_ordered-(item.quantity_received||0),0);if(!rem){setError('This PO line is already fully received.');setCode('');return}setModal({item,quantity:1,expiry:'',batch:'',cost:String(item.unit_cost??''),notes:''});setCode('')};
 const save=async()=>{if(!modal||!po)return;if(modal.quantity<1||!modal.expiry){setError('Received quantity and expiry date are required.');return}setBusy(true);setError('');try{const inv=await ensureInvoice();const {data,error}=await supabase.rpc('receive_purchase_scan_with_invoice',{p_purchase_order_id:po.id,p_supplier_invoice_id:inv,p_gtin:modal.item.products?.gtin||modal.item.gtin,p_quantity:modal.quantity,p_expiry_date:modal.expiry,p_batch_id:modal.batch||null,p_invoice_unit_cost:Number(modal.cost)||modal.item.unit_cost,p_notes:modal.notes||null});if(error)throw error;const {error:re}=await supabase.rpc('reconcile_purchase',{p_purchase_order_id:po.id,p_supplier_invoice_id:inv});if(re)throw re;await loadItems(po.id);setModal(null);setOk(`Received ${modal.quantity} × ${modal.item.products?.name||modal.item.supplier_product_name}. Inventory and reconciliation updated.`)}catch(e:any){setError(e.message||'Receiving failed.')}finally{setBusy(false);setTimeout(()=>scanRef.current?.focus(),50)}};
 const ordered=items.reduce((n,i)=>n+i.quantity_ordered,0),received=items.reduce((n,i)=>n+(i.quantity_received||0),0),remain=ordered-received;
 return <div className="p-6 max-w-[1600px] mx-auto space-y-6"><header className="flex flex-col lg:flex-row lg:justify-between gap-4"><div><h1 className="text-2xl font-black text-white uppercase">Warehouse Receiving</h1><p className="text-sm text-slate-500">Select PO → enter invoice → scan GTIN → confirm quantity, batch and expiry.</p></div><div className="flex gap-2"><button onClick={()=>router.push('/inventory-management/purchase-reconciliation')} className="px-4 py-3 bg-slate-800 text-white rounded-xl font-bold">Reconciliation</button><button onClick={()=>router.push('/inventory-management/purchase-orders')} className="px-4 py-3 bg-slate-800 text-white rounded-xl font-bold">Purchase Orders</button></div></header>{error&&<div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-300">{error}</div>}{ok&&<div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300">✓ {ok}</div>}
 <div className="grid xl:grid-cols-3 gap-5"><section className="bg-slate-900/60 border border-slate-800 rounded-3xl p-5"><h2 className="text-xs font-black text-cyan-400 uppercase mb-3">Purchase Order</h2><select value={po?.id||''} onChange={e=>setPo(pos.find(x=>x.id===e.target.value)||null)} className="w-full bg-slate-800 border border-slate-700 rounded-xl p-3 text-white"><option value="">Select open PO…</option>{pos.map(x=><option key={x.id} value={x.id}>{x.po_number} · {x.suppliers?.name||'Supplier'}</option>)}</select>{po&&<div className="grid grid-cols-3 gap-2 mt-4 text-xs"><div className="bg-slate-800 p-3 rounded-xl"><span className="text-slate-500 block">Ordered</span><b>{ordered}</b></div><div className="bg-slate-800 p-3 rounded-xl"><span className="text-slate-500 block">Received</span><b className="text-emerald-400">{received}</b></div><div className="bg-slate-800 p-3 rounded-xl"><span className="text-slate-500 block">Remaining</span><b className="text-amber-400">{remain}</b></div></div>}</section>
 <section className="xl:col-span-2 bg-slate-900/60 border border-slate-800 rounded-3xl p-5"><h2 className="text-xs font-black text-cyan-400 uppercase mb-3">Supplier Invoice — required for this delivery</h2><div className="grid md:grid-cols-5 gap-3"><input placeholder="Invoice # *" value={invoiceNo} onChange={e=>setInvoiceNo(e.target.value)} className="field"/><input type="date" value={invoiceDate} onChange={e=>setInvoiceDate(e.target.value)} className="field"/><input type="number" placeholder="Invoice total" value={invoiceTotal} onChange={e=>setInvoiceTotal(e.target.value)} className="field"/><input type="number" placeholder="VAT" value={vat} onChange={e=>setVat(e.target.value)} className="field"/><label className="field cursor-pointer">{file?file.name:'Upload invoice'}<input type="file" accept="application/pdf,image/*" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><input type="number" placeholder="Shipping / delivery cost" value={shipping} onChange={e=>setShipping(e.target.value)} className="field mt-3 w-full md:w-64"/><style jsx>{`.field{background:#1e293b;border:1px solid #334155;border-radius:.75rem;padding:.75rem;color:white;width:100%}`}</style></section></div>
 <section className="bg-slate-900/60 border border-cyan-500/20 rounded-3xl overflow-hidden"><div className="p-5 border-b border-slate-800 flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><h2 className="text-sm font-black text-white uppercase">GTIN Scanner</h2><p className="text-[10px] text-slate-500">Keep the scanner field focused. Most USB scanners act like a keyboard and press Enter.</p></div><form onSubmit={e=>{e.preventDefault();scan()}} className="flex gap-2"><input ref={scanRef} autoFocus value={code} onChange={e=>setCode(e.target.value)} disabled={!po} placeholder="Scan GTIN…" className="w-80 bg-slate-800 border border-cyan-500/40 rounded-xl px-4 py-3 text-white font-mono"/><button className="px-5 py-3 bg-cyan-600 text-white rounded-xl font-black">SCAN</button></form></div>{!po?<div className="p-10 text-center text-slate-600">Select a PO to start receiving.</div>:<div className="divide-y divide-slate-800">{items.map(i=><div key={i.id} className="p-4 flex justify-between gap-4"><div><b className="text-white">{i.products?.name||i.supplier_product_name}</b><div className="text-[10px] text-slate-500 font-mono">GTIN {i.products?.gtin||i.gtin||'—'} · SKU {i.products?.sku||i.supplier_sku||'—'}</div></div><div className="text-xs flex gap-5"><span>PO <b>{i.quantity_ordered}</b></span><span className="text-emerald-400">Received <b>{i.quantity_received||0}</b></span><span className="text-amber-400">Left <b>{Math.max(i.quantity_ordered-(i.quantity_received||0),0)}</b></span></div></div>)}</div>}</section>
 {modal&&<div className="fixed inset-0 z-50 bg-black/75 flex items-center justify-center p-4"><div className="w-full max-w-lg bg-slate-900 border border-slate-700 rounded-3xl p-6 space-y-5"><div><span className="text-[10px] font-black text-cyan-400 uppercase">Product found</span><h2 className="text-xl font-black text-white">{modal.item.products?.name||modal.item.supplier_product_name}</h2><p className="text-xs text-slate-500 font-mono">GTIN {modal.item.products?.gtin||modal.item.gtin} · PO remaining {Math.max(modal.item.quantity_ordered-(modal.item.quantity_received||0),0)}</p></div><div className="grid grid-cols-2 gap-3"><label className="text-xs text-slate-400">Quantity<input type="number" min="1" max={Math.max(modal.item.quantity_ordered-(modal.item.quantity_received||0),1)} value={modal.quantity} onChange={e=>setModal({...modal,quantity:Number(e.target.value)||0})} className="field"/></label><label className="text-xs text-slate-400">Expiry *<input type="date" value={modal.expiry} onChange={e=>setModal({...modal,expiry:e.target.value})} className="field"/></label><label className="text-xs text-slate-400">Batch / Lot<input value={modal.batch} onChange={e=>setModal({...modal,batch:e.target.value})} className="field"/></label><label className="text-xs text-slate-400">Invoice unit cost<input type="number" step="0.0001" value={modal.cost} onChange={e=>setModal({...modal,cost:e.target.value})} className="field"/></label></div><label className="text-xs text-slate-400">Notes<textarea value={modal.notes} onChange={e=>setModal({...modal,notes:e.target.value})} rows={2} className="field"/></label><div className="flex justify-end gap-3"><button onClick={()=>setModal(null)} className="px-5 py-3 bg-slate-800 text-white rounded-xl font-bold">Cancel</button><button disabled={busy} onClick={save} className="px-6 py-3 bg-emerald-600 text-white rounded-xl font-black">{busy?'Saving…':'Confirm Receipt'}</button></div></div></div>}
 </div>;
}
