import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.45.4";

const jsonHeaders = { "Content-Type": "application/json", "Cache-Control": "no-store" };
function response(status: number, body: Record<string, unknown>) { return new Response(JSON.stringify(body), { status, headers: jsonHeaders }); }
async function sha256Hex(input: string): Promise<string> { const bytes = new TextEncoder().encode(input); const digest = await crypto.subtle.digest("SHA-256", bytes); return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join(""); }
function normalizeCheckName(value: unknown): string { const raw = String(value ?? "unknown").replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/[\s-]+/g, "_").replace(/[^a-zA-Z0-9_]/g, "").toLowerCase(); const aliases: Record<string, string> = { metadescription: "meta_description", meta_descriptions: "meta_description", page_titles: "title", pagetitle: "title", pagespeed: "page_speed", page_speed_score: "page_speed", ogtags: "og_tags", open_graph: "og_tags", alt_tags: "image_alt_text", image_alt_texts: "image_alt_text", noindexnofollow: "noindex_nofollow", orphanpages: "orphan_pages", redirected_urls: "internal_redirects", redirects: "internal_redirects", canonical_urls: "canonical", structureddata: "structured_data" }; return aliases[raw] ?? raw; }
function normalizeSeverity(task: Record<string, unknown>): "low" | "medium" | "high" | "critical" { const direct = String(task.severity ?? "").toLowerCase(); if (["low", "medium", "high", "critical"].includes(direct)) return direct as any; const result = String(task.result ?? "").toLowerCase(); if (result === "error") return "critical"; if (result === "warning") return "high"; if (result === "suggestion") return "medium"; return "medium"; }
function collectTasks(payload: Record<string, unknown>): Array<Record<string, unknown> & { _category?: string }> { const out: Array<Record<string, unknown> & { _category?: string }> = []; const add = (value: unknown, category?: string) => { if (Array.isArray(value)) { for (const item of value) if (item && typeof item === "object") out.push({ ...(item as Record<string, unknown>), _category: category }); return; } if (value && typeof value === "object") { const obj = value as Record<string, unknown>; if (Array.isArray(obj.tasks)) add(obj.tasks, category); } }; add(payload.tasks); const todo = (payload.todo ?? payload.to_do ?? (payload.data as Record<string, unknown> | undefined)?.todo) as unknown; if (Array.isArray(todo)) add(todo); if (todo && typeof todo === "object" && !Array.isArray(todo)) for (const [category, bucket] of Object.entries(todo as Record<string, unknown>)) add(bucket, category); return out; }

Deno.serve(async (req: Request) => {
  if (req.method === "GET") return response(200, { ok: true, service: "centralhub-site-health-webhook", mode: "secured" });
  if (req.method !== "POST") return response(405, { ok: false, error: "method_not_allowed" });
  const url = new URL(req.url); const storeSlug = (url.searchParams.get("store") ?? "").trim().toLowerCase(); const token = url.searchParams.get("token") ?? req.headers.get("x-site-health-token") ?? "";
  if (!storeSlug || !token) return response(401, { ok: false, error: "missing_webhook_credentials" });
  const supabaseUrl = Deno.env.get("SUPABASE_URL"); const serviceRole = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!supabaseUrl || !serviceRole) return response(500, { ok: false, error: "server_not_configured" });
  const db = createClient(supabaseUrl, serviceRole, { auth: { persistSession: false, autoRefreshToken: false } });
  const { data: store, error: storeError } = await db.from("stores").select("id,slug,name,domain").eq("slug", storeSlug).maybeSingle(); if (storeError || !store) return response(404, { ok: false, error: "unknown_store" });
  const { data: config, error: configError } = await db.from("site_health_store_configs").select("*").eq("store_id", store.id).maybeSingle(); if (configError || !config) return response(403, { ok: false, error: "site_health_not_configured" });
  if (!config.master_enabled || config.kill_switch || !config.siteguru_enabled) return response(202, { ok: true, accepted: false, reason: "automation_disabled" });
  const incomingHash = await sha256Hex(token); if (!config.webhook_token_hash || incomingHash !== config.webhook_token_hash) return response(401, { ok: false, error: "invalid_webhook_token" });
  const rawBody = await req.text(); let payload: Record<string, unknown>; try { payload = JSON.parse(rawBody || "{}") as Record<string, unknown>; } catch { return response(400, { ok: false, error: "invalid_json" }); }
  const payloadDomain = String(payload.domain ?? payload.website ?? (payload.site && typeof payload.site === "object" ? (payload.site as Record<string, unknown>).domain : payload.site) ?? "").replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/$/, "").toLowerCase();
  const expectedDomain = String(config.domain ?? store.domain ?? "").replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/$/, "").toLowerCase(); if (payloadDomain && expectedDomain && payloadDomain !== expectedDomain) return response(400, { ok: false, error: "domain_mismatch" });
  const eventType = String(payload.event_type ?? payload.event ?? payload.type ?? "website_audit_completed"); const externalEventId = payload.event_id ?? payload.id ?? (payload.data && typeof payload.data === "object" ? (payload.data as Record<string, unknown>).id : null); const eventFingerprint = await sha256Hex(String(externalEventId ?? `${store.id}|${eventType}|${rawBody}`));
  const healthScoreRaw = payload.health_score ?? payload.healthScore ?? (payload.data && typeof payload.data === "object" ? (payload.data as Record<string, unknown>).health_score : null); const healthScore = healthScoreRaw == null || Number.isNaN(Number(healthScoreRaw)) ? null : Math.round(Number(healthScoreRaw));
  const { data: existingRun } = await db.from("site_health_runs").select("id,status").eq("store_id", store.id).eq("source", "siteguru").eq("event_fingerprint", eventFingerprint).maybeSingle(); if (existingRun) return response(200, { ok: true, duplicate: true, run_id: existingRun.id, status: existingRun.status });
  const { data: run, error: runError } = await db.from("site_health_runs").insert({ store_id: store.id, source: "siteguru", event_type: eventType, external_event_id: externalEventId == null ? null : String(externalEventId), event_fingerprint: eventFingerprint, health_score: healthScore, status: "received", payload }).select("id").single(); if (runError || !run) return response(500, { ok: false, error: "run_insert_failed" });
  const { data: rulesData } = await db.from("site_health_rules").select("*"); const rules = new Map<string, Record<string, unknown>>((rulesData ?? []).map((r: Record<string, unknown>) => [String(r.check_name), r])); const tasks = collectTasks(payload); let queued = 0, blocked = 0, open = 0;
  for (const task of tasks) { const checkName = normalizeCheckName(task.checkName ?? task.check_name ?? task.check ?? task.name ?? task.title); const rule = rules.get(checkName); const riskLevel = String(rule?.default_risk_level ?? "high"); const autoFixAllowed = Boolean(rule?.auto_fix_allowed ?? false); const requiresPreview = Boolean(rule?.requires_preview ?? true); const pageUrl = task.url ?? task.page_url ?? task.page ?? null; const reportUrl = task.report_url ?? task.reportUrl ?? null; const issueFingerprint = await sha256Hex(`${store.id}|siteguru|${checkName}|${String(reportUrl ?? "")}|${String(pageUrl ?? "")}`); const canQueue = config.auto_fix_enabled && autoFixAllowed && ["guarded", "autonomous"].includes(config.execution_mode) && riskLevel !== "blocked" && riskLevel !== "high"; const status = riskLevel === "blocked" || Boolean(rule?.requires_manual_approval) ? "blocked" : canQueue ? "queued" : "open"; if (status === "queued") queued++; else if (status === "blocked") blocked++; else open++;
    const record = { store_id: store.id, run_id: run.id, source: "siteguru", fingerprint: issueFingerprint, check_name: checkName, title: String(task.title ?? checkName.replaceAll("_", " ")), description: task.description == null ? null : String(task.description), category: String(task.type ?? task._category ?? rule?.category ?? "unknown"), severity: normalizeSeverity(task), risk_level: riskLevel, auto_fix_allowed: autoFixAllowed, requires_preview: requiresPreview, affected_pages: task.affectedPages == null && task.affected_pages == null ? null : Number(task.affectedPages ?? task.affected_pages), page_url: pageUrl == null ? null : String(pageUrl), report_url: reportUrl == null ? null : String(reportUrl), status, raw: task, last_seen_at: new Date().toISOString(), resolved_at: null };
    const { data: existingIssue } = await db.from("site_health_issues").select("id,first_seen_at,status").eq("store_id", store.id).eq("fingerprint", issueFingerprint).maybeSingle(); if (existingIssue) await db.from("site_health_issues").update(record).eq("id", existingIssue.id); else await db.from("site_health_issues").insert(record);
  }
  await db.from("site_health_runs").update({ status: queued > 0 ? "queued" : "normalized", processed_at: new Date().toISOString() }).eq("id", run.id); await db.from("site_health_store_configs").update({ last_webhook_at: new Date().toISOString(), last_audit_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("store_id", store.id);
  return response(200, { ok: true, run_id: run.id, tasks: tasks.length, queued, blocked, open, health_score: healthScore });
});
