import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
const ALLOWED_EVENTS=new Set(['page_view','session_start','session_heartbeat','search','view_item','view_item_list','select_item','add_to_cart','remove_from_cart','view_cart','begin_checkout','add_payment_info','purchase','refund','login','sign_up','select_promotion','view_promotion']);
const CLICK_KEYS=['gclid','gbraid','wbraid','fbclid','ttclid'];const MAX_BODY=32000;const MAX_METADATA_KEYS=40;
function cleanText(v:unknown,max=500){if(typeof v!=='string')return null;const x=v.trim();return x?x.slice(0,max):null;}
function cleanMetadata(v:unknown,d=0):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v)||d>3)return{};const o:Record<string,unknown>={};for(const[k,val]of Object.entries(v as Record<string,unknown>).slice(0,MAX_METADATA_KEYS)){if(!/^[a-zA-Z0-9_.-]{1,80}$/.test(k)||/email|phone|password|token|secret|address|card|payment/i.test(k))continue;if(typeof val==='string')o[k]=val.slice(0,500);else if(typeof val==='number'||typeof val==='boolean'||val===null)o[k]=val;else if(Array.isArray(val))o[k]=val.slice(0,50).map(i=>i===null||typeof i==='string'||typeof i==='number'||typeof i==='boolean'?(typeof i==='string'?i.slice(0,500):i):cleanMetadata(i,d+1));else if(d<3)o[k]=cleanMetadata(val,d+1);}return o;}
function json(status:number,body:Record<string,unknown>,origin:string|null){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':origin||'*','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type, authorization','vary':'Origin'}});}
function isUuid(v:string|null){return!!v&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
function sourceClass(s0:string|null,m0:string|null,r0:string|null,c:string|null){const s=(s0||'').toLowerCase(),m=(m0||'').toLowerCase(),r=(r0||'').toLowerCase();if(c&&(s.startsWith('google')||m.includes('cpc')||m.includes('ppc')))return'google_ads';if(c&&(s.startsWith('facebook')||s.startsWith('instagram')||s.startsWith('meta')))return'meta_ads';if(c&&s.startsWith('tiktok'))return'tiktok_ads';if(s)return s;if(!r)return'direct';if(/google\.|googleusercontent\./.test(r))return'google_organic';if(/bing\./.test(r))return'bing_organic';if(/yahoo\./.test(r))return'yahoo_organic';if(/duckduckgo\./.test(r))return'duckduckgo_organic';if(/facebook\.|instagram\./.test(r))return'facebook_instagram';if(/tiktok\./.test(r))return'tiktok';if(/youtube\./.test(r))return'youtube';return'referral';}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':origin||'*','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type, authorization','vary':'Origin'}});if(req.method!=='POST')return json(405,{error:'method_not_allowed'},origin);const len=Number(req.headers.get('content-length')||0);if(len>MAX_BODY)return json(413,{error:'payload_too_large'},origin);let body:any;try{body=await req.json();}catch{return json(400,{error:'invalid_json'},origin);}
const trackingId=cleanText(body?.tracking_id,200),eventType=cleanText(body?.event_type,80),sessionKey=cleanText(body?.session_id,200),clientEventId=cleanText(body?.client_event_id,200);if(!trackingId||!eventType||!sessionKey)return json(400,{error:'tracking_id_event_type_session_id_required'},origin);if(!ALLOWED_EVENTS.has(eventType))return json(400,{error:'unsupported_event'},origin);
const{data:c,error:e}=await supabase.from('analytics_store_tracking_configs').select('store_id,enabled').eq('public_tracking_id',trackingId).maybeSingle();if(e||!c?.enabled)return json(403,{error:'invalid_tracking_id'},origin);const storeId:string=c.store_id;
const{data:store,error:storeError}=await supabase.from('stores').select('id,domain').eq('id',storeId).maybeSingle();if(storeError||!store)return json(403,{error:'invalid_store'},origin);if(origin){try{const host=new URL(origin).hostname.toLowerCase().replace(/^www\./,'');const d=String(store.domain||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').replace(/\/$/,'');if(d&&host!==d)return json(403,{error:'origin_not_allowed'},origin);}catch{return json(403,{error:'invalid_origin'},origin);}}
if(clientEventId){const{data:existing}=await supabase.from('analytics_events').select('id').eq('store_id',storeId).eq('client_event_id',clientEventId).maybeSingle();if(existing)return json(202,{accepted:true,duplicate:true},origin);}
const metadata=cleanMetadata(body?.metadata),visitorId=cleanText(body?.visitor_id,200);if(visitorId)metadata.visitor_id=visitorId;if(trackingId)metadata.tracking_id=trackingId;const clickId=CLICK_KEYS.map(k=>cleanText(body?.[k],300)).find(Boolean)||cleanText(body?.click_id,300);const utmSource=cleanText(body?.utm_source,200),utmMedium=cleanText(body?.utm_medium,200),utmCampaign=cleanText(body?.utm_campaign,500),utmContent=cleanText(body?.utm_content,500),utmTerm=cleanText(body?.utm_term,500),referrer=cleanText(body?.referrer,2000),url=cleanText(body?.url,2000);const source=sourceClass(utmSource,utmMedium,referrer,clickId);const rawOrderId=cleanText(body?.order_id,100),orderId=isUuid(rawOrderId)?rawOrderId:null;const rawProductId=cleanText(String(metadata.item_id??''),100),productId=isUuid(rawProductId)?rawProductId:null;const now=body?.timestamp?new Date(body.timestamp).toISOString():new Date().toISOString();
const{data:sessionId,error:sessionError}=await supabase.rpc('analytics_touch_session',{p_store_id:storeId,p_session_key:sessionKey,p_anonymous_id:visitorId,p_source:source,p_medium:utmMedium,p_campaign:utmCampaign,p_content:utmContent,p_term:utmTerm,p_referrer:referrer,p_landing_page:url,p_last_seen_at:now,p_event_name:eventType,p_order_id:orderId});if(sessionError||!sessionId)return json(500,{error:'session_write_failed'},origin);
const purchaseValue=typeof metadata.value==='number'?metadata.value:null;const itemPrice=typeof metadata.price==='number'?metadata.price:null;const productValue=eventType==='purchase'?purchaseValue:itemPrice;const eventRow={store_id:storeId,session_id:sessionId,anonymous_id:visitorId,customer_id:null,order_id:orderId,event_name:eventType,page_url:url,page_title:cleanText(body?.page_title,500),product_id:productId,product_name:cleanText(String(metadata.item_name??''),500),product_value:productValue,currency:'GBP',source,medium:utmMedium,campaign:utmCampaign,campaign_id:null,content:utmContent,term:utmTerm,referrer,country:null,region:null,city:null,device_category:null,metadata:{...metadata,click_id:clickId},occurred_at:now,client_event_id:clientEventId};
const{error:eventError}=await supabase.from('analytics_events').insert(eventRow);if(eventError){if(clientEventId&&eventError.code==='23505')return json(202,{accepted:true,duplicate:true},origin);return json(500,{error:'analytics_event_write_failed'},origin);}
const marketingRow={store_id:storeId,session_id:sessionKey,customer_id:null,order_id:orderId,event_type:eventType,event_source:cleanText(body?.event_source,20)||'web',url,referrer,utm_source:utmSource,utm_medium:utmMedium,utm_campaign:utmCampaign,utm_content:utmContent,utm_term:utmTerm,click_id:clickId,metadata,ip_address:null,user_agent:cleanText(req.headers.get('user-agent'),1000),timestamp:now,client_event_id:clientEventId};const{error:marketingError}=await supabase.from('marketing_events').insert(marketingRow);if(marketingError&&!(clientEventId&&marketingError.code==='23505'))return json(500,{error:'marketing_event_write_failed'},origin);return json(202,{accepted:true},origin);});