'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useStore } from '@/lib/store/useStore';
import { supabase } from '@/lib/supabase';

const input='rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-white outline-none focus:border-blue-500';
export default function BudgetsLiveClient(){
 const {selectedStore}=useStore(); const storeId=selectedStore?.id||''; const [campaigns,setCampaigns]=useState<any[]>([]); const [metrics,setMetrics]=useState<any[]>([]); const [providers,setProviders]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saving,setSaving]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');let cq=supabase.from('marketing_campaigns').select('id,name,provider_id,status,budget_type,budget_amount,currency,start_date,end_date').order('created_at',{ascending:false});let mq=supabase.from('marketing_metrics').select('provider_id,spend,conversion_value,conversions,date').order('date',{ascending:false});if(storeId){cq=cq.eq('store_id',storeId);mq=mq.eq('store_id',storeId);}const [c,m,p]=await Promise.all([cq,mq,supabase.from('marketing_providers').select('id,display_name').eq('is_active',true).order('display_name')]);if(c.error)setError(c.error.message);else setCampaigns(c.data||[]);if(m.error)setError(m.error.message);else setMetrics(m.data||[]);if(p.error)setError(p.error.message);else setProviders(p.data||[]);setLoading(false)},[storeId]);
 useEffect(()=>{load()},[load]);
 const monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0); const monthISO=monthStart.toISOString();
 const monthCampaigns=campaigns.filter(c=>!c.start_date||new Date(c.start_date)<=new Date());
 const spend=metrics.filter(m=>m.date>=monthISO.slice(0,10)).reduce((s,m)=>s+Number(m.spend||0),0); const budget=monthCampaigns.reduce((s,c)=>s+Number(c.budget_amount||0),0); const remaining=Math.max(0,budget-spend); const days=new Date().getDate(); const daily=days?spend/days:0; const forecast=daily*new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(); const roas=spend?metrics.reduce((s,m)=>s+Number(m.conversion_value||0),0)/spend:0;
 const byProvider=useMemo(()=>{const map:Record<string,{allocated:number;spent:number;revenue:number}>={};campaigns.forEach(c=>{const k=c.provider_id;map[k]??={allocated:0,spent:0,revenue:0};map[k].allocated+=Number(c.budget_amount||0)});metrics.forEach(m=>{const k=m.provider_id;map[k]??={allocated:0,spent:0,revenue:0};map[k].spent+=Number(m.spend||0);map[k].revenue+=Number(m.conversion_value||0)});return Object.entries(map).map(([provider_id,v])=>({...v,provider_id,roas:v.spent?v.revenue/v.spent:0}))},[campaigns,metrics]);
 const providerName=(id:string)=>providers.find(p=>p.id===id)?.display_name||id;
 const updateBudget=async(c:any)=>{setSaving(c.id);const value=prompt('New campaign budget',String(c.budget_amount??0));if(value!==null){const n=Number(value);if(Number.isFinite(n)&&n>=0){const {error:e}=await supabase.from('marketing_campaigns').update({budget_amount:n,updated_at:new Date().toISOString()}).eq('id',c.id).eq('store_id',storeId);if(e)setError(e.message);else await load()}}setSaving(null)};
 return <div className="p-6 space-y-6 max-w-7xl mx-auto text-white"><div className="flex justify-between flex-wrap gap-4"><div><h1 className="text-3xl font-black">Marketing Budget Manager</h1><p className="text-slate-400">Budget and spend calculated from live campaigns and marketing metrics.</p></div><button onClick={load} className="px-4 py-2 rounded-lg border border-slate-700">Refresh</button></div>{error&&<div className="p-3 rounded-lg bg-red-500/10 border border-red-500/30 text-red-300">{error}</div>}
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3"><Stat l="Allocated" v={`£${budget.toFixed(2)}`}/><Stat l="Spent" v={`£${spend.toFixed(2)}`}/><Stat l="Remaining" v={`£${remaining.toFixed(2)}`}/><Stat l="Forecast" v={`£${forecast.toFixed(2)}`}/><Stat l="ROAS" v={`${roas.toFixed(2)}x`}/></div>
 <div className="rounded-2xl border border-slate-800 bg-slate-950 overflow-hidden"><div className="p-4 border-b border-slate-800 font-bold">Campaign allocations</div>{loading?<div className="p-8 text-slate-400">Loading…</div>:campaigns.length===0?<div className="p-10 text-center text-slate-500">No campaigns to budget yet.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-900"><tr>{['Campaign','Provider','Type','Budget','Status','Action'].map(h=><th key={h} className="p-3 text-left text-slate-400">{h}</th>)}</tr></thead><tbody>{campaigns.map(c=><tr key={c.id} className="border-t border-slate-800"><td className="p-3 font-semibold">{c.name}</td><td className="p-3">{providerName(c.provider_id)}</td><td className="p-3">{c.budget_type||'daily'}</td><td className="p-3">£{Number(c.budget_amount||0).toFixed(2)} {c.currency||'GBP'}</td><td className="p-3">{c.status}</td><td className="p-3"><button disabled={saving===c.id} onClick={()=>updateBudget(c)} className={`${input} text-xs`}>{saving===c.id?'Saving…':'Adjust budget'}</button></td></tr>)}</tbody></table></div>}</div>
 <div className="rounded-2xl border border-slate-800 bg-slate-950 overflow-hidden"><div className="p-4 border-b border-slate-800 font-bold">Channel performance</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-900"><tr>{['Channel','Allocated','Spent','Revenue','ROAS'].map(h=><th key={h} className="p-3 text-left text-slate-400">{h}</th>)}</tr></thead><tbody>{byProvider.map(r=><tr key={r.provider_id} className="border-t border-slate-800"><td className="p-3 font-semibold">{providerName(r.provider_id)}</td><td className="p-3">£{r.allocated.toFixed(2)}</td><td className="p-3">£{r.spent.toFixed(2)}</td><td className="p-3">£{r.revenue.toFixed(2)}</td><td className="p-3 text-cyan-400 font-bold">{r.roas.toFixed(2)}x</td></tr>)}</tbody></table></div></div>
 </div>;
}
function Stat({l,v}:{l:string;v:string}){return <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4"><div className="text-xs text-slate-500 uppercase">{l}</div><div className="text-xl font-black mt-1">{v}</div></div>}
