'use client';

import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { Card } from '@/lib/design-system';
import { formatCurrency } from '@/lib/utils/currency';

type Invoice = { id:string; invoice_number:string; invoice_date:string; supplier_id:string|null; total_amount:number|null; actual_landed_cost:number|null; supplier_invoice_profit:number|null; suppliers?: { name:string }|null };

export default function SupplierInvoiceProfitClient(){
 const [rows,setRows]=useState<Invoice[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);const {data,error}=await supabase.from('supplier_invoices').select('id,invoice_number,invoice_date,supplier_id,total_amount,actual_landed_cost,supplier_invoice_profit,suppliers(name)').order('invoice_date',{ascending:false}).limit(200);if(error)setError(error.message);setRows((data||[]) as unknown as Invoice[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 const totalProfit=rows.reduce((a,r)=>a+Number(r.supplier_invoice_profit||0),0); const totalCost=rows.reduce((a,r)=>a+Number(r.actual_landed_cost||0),0);
 return <Card className="p-6 bg-slate-900 border-slate-800 rounded-3xl"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3 mb-5"><div><p className="text-[10px] text-cyan-400 font-black uppercase tracking-widest">Supplier Invoice Actuals</p><h2 className="text-xl font-black text-white">Invoice-derived Profit</h2><p className="text-xs text-slate-500 mt-1">Uses supplier invoice landed cost including allocated direct costs, compared with the current product selling price.</p></div><button onClick={load} className="px-3 py-2 rounded-xl bg-slate-800 text-white text-[10px] font-black uppercase">Refresh</button></div>{error&&<p className="text-sm text-rose-300 mb-4">{error}</p>}<div className="grid grid-cols-2 gap-3 mb-5"><div className="rounded-2xl bg-slate-950 p-4"><p className="text-[10px] text-slate-500 uppercase font-black">Landed Cost</p><p className="text-xl font-black text-amber-300">{formatCurrency(totalCost)}</p></div><div className="rounded-2xl bg-slate-950 p-4"><p className="text-[10px] text-slate-500 uppercase font-black">Invoice Profit</p><p className={`text-xl font-black ${totalProfit>=0?'text-emerald-300':'text-rose-300'}`}>{formatCurrency(totalProfit)}</p></div></div>{loading?<p className="text-sm text-slate-500">Loading invoice actuals…</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-[9px] uppercase tracking-widest text-slate-500 border-b border-slate-800"><th className="text-left py-3">Invoice</th><th className="text-left">Supplier</th><th className="text-right">Landed Cost</th><th className="text-right">Invoice Profit</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-slate-800/60"><td className="py-3 font-bold text-white">{r.invoice_number}</td><td className="text-slate-400">{r.suppliers?.name||'—'}</td><td className="text-right text-amber-300">{formatCurrency(Number(r.actual_landed_cost||0))}</td><td className={`text-right font-black ${Number(r.supplier_invoice_profit||0)>=0?'text-emerald-300':'text-rose-300'}`}>{formatCurrency(Number(r.supplier_invoice_profit||0))}</td></tr>)}</tbody></table></div>}</Card>
}
