'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { formatCurrency } from '@/lib/utils/currency';

type Ledger = { id:string; code:string; name:string; ledger_type:string; pnl_class:string; pricing_relevant:boolean; description:string|null; is_system:boolean; is_active:boolean };
type Tx = { id:string; transaction_date:string; description:string; merchant:string|null; reference:string|null; type:string; amount:number; reconciliation_status:string|null; transaction_category:string|null; ledger_account_id:string|null };

const typeOptions=[['income','Income'],['expense','Expense'],['asset','Asset'],['liability','Liability'],['equity','Equity'],['internal','Internal / transfer']];
const pnlOptions=[['revenue','Revenue'],['other_income','Other income'],['cogs','COGS'],['variable_expense','Variable expense'],['operating_expense','Operating expense'],['finance_cost','Finance cost'],['tax','Tax'],['other_expense','Other expense'],['none','No P&L impact']];

export default function FinanceLedgerClient(){
 const [ledgers,setLedgers]=useState<Ledger[]>([]); const [tx,setTx]=useState<Tx[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
 const [form,setForm]=useState({code:'',name:'',ledger_type:'expense',pnl_class:'operating_expense',pricing_relevant:true,description:''});
 const [filter,setFilter]=useState('all'); const [search,setSearch]=useState('');
 const fetchAllBankTransactions=async()=>{const pageSize=1000;const all:Tx[]=[];for(let from=0;;from+=pageSize){const{data,error}=await supabase.from('bank_transactions').select('id,transaction_date,description,merchant,reference,type,amount,reconciliation_status,transaction_category,ledger_account_id').order('transaction_date',{ascending:false}).range(from,from+pageSize-1);if(error)return{data:all,error};all.push(...((data||[])as Tx[]));if(!data||data.length<pageSize)break}return{data:all,error:null}};
 const load=useCallback(async()=>{setLoading(true);setError(null);const [l,t]=await Promise.all([supabase.from('finance_ledger_accounts').select('*').eq('is_active',true).order('code'),fetchAllBankTransactions()]);if(l.error)setError(l.error.message);if(t.error)setError(t.error.message);setLedgers((l.data||[]) as Ledger[]);setTx((t.data||[]) as Tx[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 const assign=async(id:string,ledgerId:string)=>{setSaving(true);setError(null);const {error}=await supabase.rpc('assign_bank_transaction_ledger',{p_transaction_id:id,p_ledger_account_id:ledgerId});if(error)setError(error.message);else setTx(rows=>rows.map(r=>r.id===id?{...r,ledger_account_id:ledgerId}:r));setSaving(false)};
 const create=async()=>{if(!form.code.trim()||!form.name.trim())return;setSaving(true);setError(null);const {data,error}=await supabase.rpc('create_finance_ledger_account',{p_code:form.code,p_name:form.name,p_ledger_type:form.ledger_type,p_pnl_class:form.pnl_class,p_pricing_relevant:form.pricing_relevant,p_description:form.description||null});if(error)setError(error.message);else{setForm({code:'',name:'',ledger_type:'expense',pnl_class:'operating_expense',pricing_relevant:true,description:''});await load()}setSaving(false)};
 const filtered=useMemo(()=>tx.filter(r=>(filter==='unassigned'? !r.ledger_account_id:filter==='pnl'? !!ledgers.find(l=>l.id===r.ledger_account_id&&l.pnl_class!=='none'):filter==='balance'? !!ledgers.find(l=>l.id===r.ledger_account_id&&l.pnl_class==='none'):true)&&(`${r.description} ${r.merchant||''} ${r.reference||''}`).toLowerCase().includes(search.toLowerCase())),[tx,filter,search,ledgers]);
 const ledgerName=(id:string|null)=>ledgers.find(l=>l.id===id)?.name||'Unassigned';
 return <div className="p-4 sm:p-6 max-w-[1700px] mx-auto space-y-6">
  <header><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] text-cyan-400 font-black uppercase tracking-[.25em]">CentralHub Finance</p></div><a href="/finance/head-advisor" className="px-3 py-2 rounded-xl bg-cyan-500 text-slate-950 text-[9px] font-black uppercase tracking-widest">Head adviser</a></div><h1 className="text-3xl font-black text-white">Chart of Accounts & Ledger</h1><p className="text-sm text-slate-500 mt-1">Create the ledger structure that decides whether a bank transaction belongs in P&L or on the balance sheet.</p></header>
  <div className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-4 text-sm text-slate-300"><b className="text-cyan-300">Rule:</b> Income and expense ledgers can affect P&L. Assets, liabilities, equity and internal transfers are <b className="text-white">never P&L</b>. They remain visible in cash/balance-sheet reporting. Pricing relevance is controlled separately.</div>
  {error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}
  <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
   <section className="xl:col-span-1 bg-slate-900 border border-slate-800 rounded-3xl p-5"><h2 className="text-lg font-black text-white">Create ledger</h2><p className="text-xs text-slate-500 mt-1">Examples: Rent, Advertising, Bank loan, Inventory asset, Supplier payable.</p><div className="space-y-3 mt-5">
    <input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Code e.g. 6050" className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-sm text-white"/>
    <input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ledger name" className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-sm text-white"/>
    <select value={form.ledger_type} onChange={e=>{const v=e.target.value;setForm({...form,ledger_type:v,pnl_class:v==='income'?'revenue':v==='expense'?'operating_expense':'none',pricing_relevant:v==='expense'})}} className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-sm text-white">{typeOptions.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select>
    <select value={form.pnl_class} onChange={e=>setForm({...form,pnl_class:e.target.value})} disabled={['asset','liability','equity','internal'].includes(form.ledger_type)} className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-sm text-white disabled:opacity-50">{pnlOptions.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select>
    <label className="flex items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={form.pricing_relevant} onChange={e=>setForm({...form,pricing_relevant:e.target.checked})} disabled={['asset','liability','equity','internal'].includes(form.ledger_type)}/> Include as pricing cost</label>
    <textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Purpose / notes" className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-sm text-white min-h-20"/>
    <button disabled={saving} onClick={create} className="w-full bg-cyan-500 text-slate-950 rounded-xl p-3 text-xs font-black uppercase tracking-widest disabled:opacity-50">Create ledger</button>
   </div></section>
   <section className="xl:col-span-2 bg-slate-900 border border-slate-800 rounded-3xl p-5"><div className="flex justify-between gap-3"><div><h2 className="text-lg font-black text-white">Ledger accounts</h2><p className="text-xs text-slate-500">{ledgers.length} active accounts</p></div><button onClick={load} className="px-3 py-2 bg-slate-800 rounded-xl text-[10px] font-black text-white">Refresh</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4">{['income','expense','asset','liability'].map(t=><div key={t} className="bg-slate-950 border border-slate-800 rounded-xl p-3"><p className="text-[9px] uppercase text-slate-500">{t}</p><p className="text-xl font-black text-white">{ledgers.filter(l=>l.ledger_type===t).length}</p></div>)}</div><div className="mt-4 max-h-80 overflow-auto space-y-2">{ledgers.map(l=><div key={l.id} className="flex items-center justify-between gap-3 bg-slate-950 border border-slate-800 rounded-xl p-3"><div><span className="font-mono text-cyan-400 text-xs">{l.code}</span><span className="ml-3 font-bold text-white">{l.name}</span><p className="text-[9px] text-slate-500 uppercase tracking-widest mt-1">{l.ledger_type} · {l.pnl_class==='none'?'NO P&L IMPACT':l.pnl_class}{l.pricing_relevant?' · PRICING':''}</p></div>{l.is_system&&<span className="text-[8px] text-slate-500">SYSTEM</span>}</div>)}</div></section>
  </div>
  <section className="bg-slate-900 border border-slate-800 rounded-3xl overflow-hidden"><div className="p-5 border-b border-slate-800"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><h2 className="text-lg font-black text-white">Assign ledgers to bank transactions</h2><p className="text-xs text-slate-500">This is the accounting treatment. Reconciliation remains a separate step.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search transaction / merchant / reference" className="bg-slate-950 border border-slate-800 rounded-xl p-2.5 text-xs text-white w-full lg:w-80"/></div><div className="flex gap-2 mt-3">{[['all','All'],['unassigned','Unassigned'],['pnl','P&L'],['balance','Balance sheet / non-P&L']].map(x=><button key={x[0]} onClick={()=>setFilter(x[0])} className={`px-3 py-2 rounded-xl text-[9px] font-black uppercase ${filter===x[0]?'bg-cyan-500 text-slate-950':'bg-slate-950 text-slate-400 border border-slate-800'}`}>{x[1]}</button>)}</div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-800/50 text-[9px] uppercase tracking-widest text-slate-500"><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Transaction</th><th className="p-3 text-right">Amount</th><th className="p-3 text-left">Ledger</th><th className="p-3 text-left">Statement treatment</th></tr></thead><tbody className="divide-y divide-slate-800">{filtered.map(r=>{const l=ledgers.find(x=>x.id===r.ledger_account_id);return <tr key={r.id}><td className="p-3 text-slate-400 whitespace-nowrap">{new Date(r.transaction_date).toLocaleDateString('en-GB')}</td><td className="p-3"><b className="text-white">{r.description}</b><div className="text-[9px] text-slate-600">{r.merchant||r.reference||''}</div></td><td className={`p-3 text-right font-black ${r.type==='credit'?'text-emerald-300':'text-rose-300'}`}>{r.type==='credit'?'+':'-'}{formatCurrency(Math.abs(Number(r.amount||0)))}</td><td className="p-3"><select disabled={saving} value={r.ledger_account_id||''} onChange={e=>e.target.value&&assign(r.id,e.target.value)} className="bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-white min-w-52"><option value="">Unassigned</option>{ledgers.map(l=><option key={l.id} value={l.id}>{l.code} · {l.name}</option>)}</select></td><td className="p-3">{l?<span className={`text-[9px] font-black uppercase ${l.pnl_class==='none'?'text-cyan-300':'text-emerald-300'}`}>{l.pnl_class==='none'?'BALANCE SHEET / NON-P&L':'P&L · '+l.pnl_class}</span>:<span className="text-[9px] text-amber-300">NEEDS LEDGER</span>}</td></tr>})}</tbody></table>{!filtered.length&&!loading&&<div className="p-10 text-center text-slate-500">No matching transactions.</div>}</div></section>
 </div>
}
