'use client';
import { useEffect,useState } from 'react';
import { channelService,CustomerCareChannel,WhatsAppChannel } from '@/lib/services/customer-care/channelService';
import { Card,Button,Badge,PageHeader } from '@/lib/design-system';
import WebhookConfigModal from './WebhookConfigModal';

const icon=(t:string)=>t==='whatsapp'?'💬':t==='instagram'?'📸':'ⓕ';
export default function ChannelsClient({params,searchParams}:{params:any;searchParams:any}){
 const [wa,setWa]=useState<WhatsAppChannel[]>([]),[all,setAll]=useState<CustomerCareChannel[]>([]),[stores,setStores]=useState<any[]>([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState<string|null>(null),[msg,setMsg]=useState(''),[webhook,setWebhook]=useState<WhatsAppChannel|null>(null);
 const load=async()=>{setLoading(true);try{const [w,u,s]=await Promise.all([channelService.getChannels(),channelService.getUnifiedChannels(),channelService.getStores()]);setWa(w);setAll(u);setStores(s)}catch(e:any){setMsg(e?.message||'Failed to load channels')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const sync=async(storeId:string)=>{setSyncing(storeId);setMsg('');try{const r=await channelService.syncMetaSocialChannels(storeId);setMsg(`Meta sync complete: ${r.channels_synced} Facebook/Instagram channel(s) discovered.`);await load()}catch(e:any){setMsg(e?.message||'Meta sync failed. Connect this store under Marketing > Integrations and grant messaging permissions first.')}finally{setSyncing(null)}};
 return <div className="p-4 md:p-6 space-y-6">
  <PageHeader title="Customer Care Channels" subtitle="One store-scoped inbox for WhatsApp, Instagram and Facebook. WhatsApp/Interakt remains untouched while Meta social channels are connected and verified." />
  {msg&&<div className="rounded-lg border border-slate-700 bg-slate-900/60 p-3 text-xs text-slate-300">{msg}</div>}
  <Card className="p-4 bg-slate-900/40 border-slate-800"><div className="flex flex-col gap-3"><div><h3 className="font-bold text-white">Connect Meta social messaging</h3><p className="text-xs text-slate-400 mt-1">First connect each store to Meta in Marketing → Integrations. Then sync here. CentralHub stores Page tokens encrypted server-side; no Meta secret is exposed to the browser.</p></div><div className="flex flex-wrap gap-2">{stores.map(s=><Button key={s.id} variant="secondary" className="text-xs" disabled={!!syncing} onClick={()=>sync(s.id)}>{syncing===s.id?'Syncing…':`Sync ${s.name}`}</Button>)}</div></div></Card>
  <div className="grid gap-4">{loading?<div className="py-10 text-center text-slate-500">Loading channels…</div>:all.map(c=><Card key={c.id} className="p-5 bg-slate-900/40 border-slate-800"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div className="flex gap-3 min-w-0"><div className="w-11 h-11 rounded-xl bg-slate-800 flex items-center justify-center text-xl">{icon(c.channel_type)}</div><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap"><h3 className="font-bold text-white capitalize">{c.channel_type}</h3><Badge variant={c.status==='active'?'success':'info'} className="uppercase text-[10px]">{c.status}</Badge><span className="text-[10px] text-slate-500 uppercase">{c.provider}</span></div><p className="text-sm text-slate-300 truncate">{c.display_name||c.external_account_id}</p><p className="text-[11px] text-slate-500">{c.store?.name||'Unlinked store'} · Account {c.external_account_id}</p>{c.last_error&&<p className="text-[11px] text-red-400 mt-1">{c.last_error}</p>}</div></div><div className="text-[11px] text-slate-500">{c.last_webhook_at?`Last webhook ${new Date(c.last_webhook_at).toLocaleString()}`:'Waiting for first webhook'}</div></div></Card>)}{!loading&&all.length===0&&<div className="py-10 text-center text-slate-500 border border-dashed border-slate-800 rounded-lg">No customer-care channels configured.</div>}</div>
  <section className="pt-2"><h4 className="text-sm font-bold text-slate-400 mb-3 uppercase tracking-widest">Existing WhatsApp configuration</h4><div className="grid gap-3">{wa.map(c=><Card key={c.id} className="p-4 bg-slate-950/30 border-slate-800"><div className="flex items-center justify-between gap-3"><div><div className="font-semibold text-white">{c.business_name||c.store?.name||'WhatsApp'}</div><div className="text-xs text-slate-500">{c.display_phone_number||'No number'} · {c.store?.name||'Unlinked'}</div></div><Button variant="secondary" className="text-xs" onClick={()=>setWebhook(c)}>WhatsApp webhook</Button></div></Card>)}</div></section>
  <div className="text-[10px] text-slate-500 leading-relaxed">Store isolation is mandatory. Instagram/Facebook identities, conversations and outbound replies are routed through the channel record for the originating store. AI never receives Meta tokens. Human takeover continues to stop automatic AI replies.</div>
  {webhook&&<WebhookConfigModal channel={webhook} onClose={()=>setWebhook(null)}/>} 
 </div>;
}
