'use client';

import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/lib/supabase';
import { OrderService } from '@/lib/services/orderService';
import { Store } from '@/lib/types';

interface ProductRow { id: string; name: string; price: number; sku: string | null; image_url: string | null; stock: number; backorder: boolean; }
interface CartItem { product: ProductRow; quantity: number; unit_price: number; }
interface Props { stores: Store[]; onClose: () => void; onCreated: () => void; }
const INPUT = 'w-full bg-slate-800/60 border border-slate-700/60 rounded-lg px-3 py-2.5 text-sm text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/50';
const LABEL = 'block text-xs font-medium text-slate-400 mb-1.5 uppercase tracking-wide';
type Step = 'details' | 'products' | 'review';

export default function CreateOrderModal({ stores, onClose, onCreated }: Props) {
  const [step, setStep] = useState<Step>('details'); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const [storeId, setStoreId] = useState(stores[0]?.id || ''); const [customerName, setCustomerName] = useState(''); const [customerEmail, setCustomerEmail] = useState(''); const [customerPhone, setCustomerPhone] = useState(''); const [address, setAddress] = useState(''); const [city, setCity] = useState(''); const [postcode, setPostcode] = useState(''); const [notes, setNotes] = useState(''); const [paymentMethod, setPaymentMethod] = useState<'cod' | 'card' | 'bank_transfer' | 'other'>('cod'); const [paymentStatus, setPaymentStatus] = useState<'paid' | 'pending'>('paid'); const [paymentRef, setPaymentRef] = useState('');
  const [products, setProducts] = useState<ProductRow[]>([]); const [productsLoading, setProductsLoading] = useState(false); const [productSearch, setProductSearch] = useState(''); const [cart, setCart] = useState<CartItem[]>([]);

  const loadProducts = useCallback(async (sid: string) => {
    if (!sid) return; setProductsLoading(true); setError('');
    try {
      const { data: prods, error: pe } = await supabase.from('products').select('id,name,price,sku,gallery_images,allow_backorder').eq('is_active', true).eq('store_id', sid).is('deleted_at', null).order('name').limit(200);
      if (pe) throw pe;
      const ids = (prods || []).map((p: any) => p.id);
      const [{ data: storeProducts }, { data: inventory }] = await Promise.all([
        ids.length ? supabase.from('store_products').select('product_id,price_override,is_active').eq('store_id', sid).in('product_id', ids) : Promise.resolve({ data: [] as any[] }),
        ids.length ? supabase.from('central_inventory').select('product_id,stock_quantity').in('product_id', ids) : Promise.resolve({ data: [] as any[] }),
      ]);
      const priceMap: Record<string, number> = {}; (storeProducts || []).forEach((r: any) => { if (r.is_active !== false && r.price_override != null) priceMap[r.product_id] = Number(r.price_override); });
      const stockMap: Record<string, number> = {}; (inventory || []).forEach((r: any) => { stockMap[r.product_id] = Number(r.stock_quantity || 0); });
      setProducts((prods || []).map((p: any) => ({ id: p.id, name: p.name, price: priceMap[p.id] ?? Number(p.price || 0), sku: p.sku, image_url: p.gallery_images?.[0] || null, stock: stockMap[p.id] ?? 0, backorder: p.allow_backorder === true })));
    } catch (e: any) { setError(e.message || 'Unable to load products'); } finally { setProductsLoading(false); }
  }, []);
  useEffect(() => { if (step === 'products') loadProducts(storeId); }, [step, storeId, loadProducts]);
  const addToCart = (product: ProductRow) => setCart(prev => { const existing = prev.find(c => c.product.id === product.id); return existing ? prev.map(c => c.product.id === product.id ? { ...c, quantity: c.quantity + 1 } : c) : [...prev, { product, quantity: 1, unit_price: product.price }]; });
  const removeFromCart = (id: string) => setCart(prev => prev.filter(c => c.product.id !== id));
  const updateQty = (id: string, qty: number) => qty <= 0 ? removeFromCart(id) : setCart(prev => prev.map(c => c.product.id === id ? { ...c, quantity: qty } : c));
  const subtotal = cart.reduce((s, c) => s + c.unit_price * c.quantity, 0); const deliveryFee = subtotal >= 50 ? 0 : 5; const total = subtotal + deliveryFee;
  const filtered = products.filter(p => !productSearch || p.name.toLowerCase().includes(productSearch.toLowerCase()) || (p.sku || '').toLowerCase().includes(productSearch.toLowerCase()));
  const validate = () => { if (!storeId || !customerName.trim() || !address.trim() || !city.trim() || !postcode.trim()) { setError('Store, customer name, address, city and postcode are required.'); return false; } setError(''); return true; };
  const submit = async () => { setSubmitting(true); setError(''); try { const { order, error: createError } = await OrderService.createOrder({ store_id: storeId, customer_name: customerName.trim(), customer_email: customerEmail.trim(), customer_phone: customerPhone.trim(), delivery_address: address.trim(), delivery_city: city.trim(), delivery_postcode: postcode.trim(), payment_method: paymentMethod, notes: notes.trim() || undefined, items: cart.map(c => ({ product_id: c.product.id, product_name: c.product.name, product_image: c.product.image_url ?? undefined, quantity: c.quantity, unit_price: c.unit_price })) }); if (createError || !order) throw new Error(createError || 'Failed to create order'); if (paymentStatus === 'paid' && paymentMethod !== 'cod') await OrderService.confirmPayment(order.id, paymentRef.trim() || undefined); onCreated(); } catch (e: any) { setError(e.message || 'Unexpected error'); } finally { setSubmitting(false); } };

  return <div className="fixed inset-0 z-50 flex items-end md:items-center justify-center p-0 md:p-4"><div className="absolute inset-0 bg-black/70" onClick={onClose}/><div className="relative bg-slate-900 border border-slate-700 rounded-t-2xl md:rounded-2xl shadow-2xl w-full md:max-w-2xl max-h-[95dvh] flex flex-col"><header className="px-5 py-4 border-b border-slate-800 flex items-center justify-between"><div><h2 className="text-lg font-bold text-white">Create Order</h2><p className="text-xs text-slate-400">Manual order entry · {step}</p></div><button onClick={onClose} className="text-slate-400 hover:text-white text-xl">×</button></header>
    <div className="flex-1 overflow-y-auto p-5">{error && <div className="mb-4 p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-sm">{error}</div>}
      {step === 'details' && <div className="space-y-5"><div><label className={LABEL}>Store *</label><select value={storeId} onChange={e => setStoreId(e.target.value)} className={INPUT}>{stores.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div className="col-span-2"><label className={LABEL}>Full Name *</label><input value={customerName} onChange={e=>setCustomerName(e.target.value)} className={INPUT}/></div><div><label className={LABEL}>Email</label><input type="email" value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)} className={INPUT}/></div><div><label className={LABEL}>Phone</label><input value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)} className={INPUT}/></div><div className="col-span-2"><label className={LABEL}>Address *</label><input value={address} onChange={e=>setAddress(e.target.value)} className={INPUT}/></div><div><label className={LABEL}>City *</label><input value={city} onChange={e=>setCity(e.target.value)} className={INPUT}/></div><div><label className={LABEL}>Postcode *</label><input value={postcode} onChange={e=>setPostcode(e.target.value)} className={INPUT}/></div></div><div className="grid grid-cols-2 gap-3"><div><label className={LABEL}>Payment Method</label><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as any)} className={INPUT}><option value="cod">Cash on Delivery</option><option value="card">Card</option><option value="bank_transfer">Bank Transfer</option><option value="other">Other</option></select></div><div><label className={LABEL}>Payment Status</label><select value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value as any)} className={INPUT}><option value="paid">Paid</option><option value="pending">Pending</option></select></div></div>{paymentStatus==='paid'&&paymentMethod!=='cod'&&<div><label className={LABEL}>Payment Reference</label><input value={paymentRef} onChange={e=>setPaymentRef(e.target.value)} className={INPUT}/></div>}<div><label className={LABEL}>Notes</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} className={INPUT}/></div></div>}
      {step === 'products' && <div className="space-y-4"><input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder="Search products…" className={INPUT}/>{productsLoading?<div className="py-10 text-center text-slate-500">Loading store products…</div>:<div className="space-y-2">{filtered.map(p=><div key={p.id} className="flex items-center gap-3 p-3 bg-slate-800/50 rounded-xl"><div className="flex-1 min-w-0"><p className="text-sm font-medium text-white truncate">{p.name}</p><p className="text-xs text-slate-500">{p.sku || 'No SKU'} · Stock {p.stock}</p></div><b className="text-white">£{p.price.toFixed(2)}</b><button disabled={!p.stock&&!p.backorder} onClick={()=>addToCart(p)} className="px-3 py-2 bg-cyan-600 disabled:opacity-40 text-white rounded-lg text-xs font-bold">Add</button></div>)}</div>}{cart.length>0&&<div className="border-t border-slate-800 pt-4 space-y-2">{cart.map(c=><div key={c.product.id} className="flex items-center gap-2 text-sm"><span className="flex-1 text-slate-200">{c.product.name}</span><input type="number" min="1" value={c.quantity} onChange={e=>updateQty(c.product.id,Number(e.target.value))} className="w-16 bg-slate-800 text-white rounded px-2 py-1"/><span className="w-20 text-right text-white">£{(c.unit_price*c.quantity).toFixed(2)}</span></div>)}</div>}</div>}
      {step === 'review' && <div className="space-y-4"><div className="bg-slate-800/50 rounded-xl p-4"><p className="text-xs text-slate-500 uppercase">Customer</p><p className="text-white font-bold">{customerName}</p><p className="text-sm text-slate-400">{address}, {city}, {postcode}</p></div><div className="bg-slate-800/50 rounded-xl p-4 space-y-2">{cart.map(c=><div key={c.product.id} className="flex justify-between text-sm"><span className="text-slate-300">{c.product.name} × {c.quantity}</span><span className="text-white">£{(c.unit_price*c.quantity).toFixed(2)}</span></div>)}<div className="border-t border-slate-700 pt-2 flex justify-between font-bold"><span className="text-slate-300">Total</span><span className="text-emerald-400">£{total.toFixed(2)}</span></div></div></div>}
    </div><footer className="px-5 py-4 border-t border-slate-800 flex justify-between"><button onClick={()=>step==='details'?onClose():setStep(step==='review'?'products':'details')} className="px-4 py-2 bg-slate-800 text-white rounded-lg">{step==='details'?'Cancel':'Back'}</button>{step!=='review'?<button onClick={()=>{if(step==='details'&&validate())setStep('products');else if(step==='products'){if(!cart.length){setError('Add at least one product.');return;}setStep('review');}}} className="px-5 py-2 bg-cyan-600 text-white rounded-lg font-bold">Next</button>:<button disabled={submitting} onClick={submit} className="px-5 py-2 bg-emerald-600 disabled:opacity-50 text-white rounded-lg font-bold">{submitting?'Creating…':'Create Order'}</button>}</footer></div></div>;
}
