import Link from 'next/link';
import type { Metadata } from 'next';
export const metadata: Metadata={title:'Website and demo terms | CentralHub',description:'Public website and fictional demo terms for CentralHub, operated by INDIVORA LTD.'};
const terms=[
 ['Scope','These terms cover the public CentralHub website and any separately labelled fictional demonstration operated by INDIVORA LTD. They are not a paid software licence, data-processing agreement, merchant agreement, tax-agent appointment or guarantee that a prospective customer can open an operational account. The private administrative system operates under its separately authorised access arrangements.'],
 ['Using the demonstration','Demo figures, transactions, reports and government integration previews are illustrative; they are not real services provided for a visitor. Do not enter taxpayer identifiers, real customer records, passwords, bank details, payroll information or confidential business documents into a fictional demo.'],
 ['Accounts and access','Access to the protected administrative system is limited to explicitly authorised users. Do not share credentials, bypass access controls or attempt to access another business’s records. Opening the public website does not create a commercial customer account.'],
 ['Tax and payments','The public tax roadmap describes intended features only. No visit, demonstration, notice acceptance or automated recommendation authorises CentralHub to connect government accounts, submit tax returns, complete customs declarations or initiate payments. Those services require an appropriately authorised and separately agreed workflow if and when implemented.'],
 ['Availability and external services','The public showcase may change during development. Any future subscription, service levels, charges, support arrangements, third-party terms, account closure, data-processing terms and liability allocation must be documented in an approved customer agreement before commercial activation. Government and council services can have their own access conditions.'],
 ['Privacy and contact','Read our privacy notice for information on handling website and service data. For written business correspondence contact INDIVORA LTD at its registered office shown on the company page. This public website does not provide a guaranteed immediate-response support channel.'],
] as const;
export default function TermsPage(){return <main className="min-h-screen bg-[#07111f] px-5 py-10 text-slate-100 sm:py-16"><div className="mx-auto max-w-4xl"><Link href="/" className="text-xl font-black text-cyan-300">CentralHub</Link><p className="mt-12 text-xs font-bold uppercase tracking-[0.18em] text-cyan-300">Public website &amp; demo terms</p><h1 className="mt-3 text-4xl font-black">Using the CentralHub showcase</h1><p className="mt-4 text-sm text-slate-400">Version 1.0 · Effective 25 September 2026</p><p className="mt-5 text-sm leading-7 text-slate-300">These terms explain the limited scope of this public website and its fictional demonstrations. They do not replace the agreement required before onboarding a paying business.</p><div className="mt-8 space-y-5">{terms.map(([heading,content])=><section key={heading} className="rounded-2xl border border-white/10 bg-[#102338] p-6"><h2 className="text-lg font-bold">{heading}</h2><p className="mt-3 text-sm leading-7 text-slate-300">{content}</p></section>)}</div><p className="mt-8 text-sm text-slate-300">Read the <Link href="/privacy" className="text-cyan-300 underline">privacy notice</Link> and <Link href="/company" className="text-cyan-300 underline">company information</Link>.</p><Link href="/" className="mt-8 inline-block font-bold text-cyan-300 underline">Return to homepage</Link></div></main>}
