export interface Store { id: string; name: string; slug: string; domain?: string | null; visibility?: boolean | null; max_display_stock: number; bucket_name?: string | null; created_at: string; }
export interface StoreBusinessIdentity { id: string; store_id: string; legal_company_name: string | null; trading_name: string | null; company_registration_number: string | null; vat_number: string | null; legal_address: string | null; city: string | null; postcode: string | null; country: string | null; business_email: string | null; business_phone: string | null; website_domain: string | null; verification_status: 'not_verified' | 'pending' | 'verified' | 'needs_review'; verification_notes: string | null; created_at: string; updated_at: string; }
export interface Product { id: string; name: string; slug: string | null; description: string | null; short_description: string | null; price: number; sale_price: number | null; compare_at_price: number | null; cost_price: number | null; image_url: string | null; category_id: string | null; sku: string | null; store_id: string | null; seo_title: string | null; is_active: boolean; is_published: boolean; is_archived: boolean; is_deleted: boolean; length_cm: number | null; width_cm: number | null; height_cm: number | null; weight_kg: number | null; weight: string | null; unit: string | null; gallery_images: string[] | null; tags: string[] | null; brand: string | null; brand_id: string | null; department: string | null; category: string | null; subcategory: string | null; category_name: string | null; stock: number | null; in_stock: boolean; target_margin: number; min_margin: number; avg_gateway_fee: number; avg_packing_cost_net: number; avg_shipping_cost_net: number; auto_price_enabled: boolean; price_override_lock: boolean; last_cost_update: string | null; warehouse_location: string | null; gtin: string | null; picking_notes: string | null; vat_rate: number | null; custom_attributes: any; backorder: boolean; allow_backorder: boolean; created_at: string; updated_at: string; }
export interface StoreProduct { id: string; product_id: string; store_id: string; name_override: string | null; description_override: string | null; price_override: number | null; stock_override: number | null; image_override: string | null; gallery_images_override: string[] | null; seo_title_override: string | null; is_active: boolean; status: string; created_at: string; updated_at: string; }
export interface ResolvedProduct { id: string; product_id?: string; name: string; description: string; price: number; image_url: string | null; category_id: string | null; sku: string | null; is_active: boolean; base_stock: number | null; store_product_id: string | null; created_at: string; updated_at: string; department?: string | null; category?: string | null; subcategory?: string | null; category_name?: string | null; brand?: string | null; unit?: string | null; weight?: number | null; product_code?: string | null; adjusted_qnty?: number | null; qnty_deducted?: number | null; adjusted_price?: number | null; price_added_percent?: number | null; price_added_amount?: number | null; product_description?: string | null; seo_title?: string | null; seo_keywords?: string | null; seo_description?: string | null; kg_id?: number | null; warehouse_location?: string | null; gtin?: string | null; picking_notes?: string | null; vat_rate?: number | null; backorder?: boolean; allow_backorder?: boolean; }
export interface BulkOperation { type: 'activate' | 'deactivate'; product_ids: string[]; store_id: string; }
export interface CentralInventory { product_id: string; stock_quantity: number; reserved_quantity: number; low_stock_threshold: number; updated_at: string; }
export type MovementType = 'IN' | 'OUT' | 'ADJUSTMENT' | 'TRANSFER'; export type LogType = 'ORDER' | 'MANUAL' | 'RETURN' | 'ADJUSTMENT' | 'SYNC' | 'TRANSFER';
export interface InventoryLog { id: string; product_id: string; product_name: string; sku: string | null; change: number; old_quantity: number | null; new_quantity: number | null; type: LogType; movement_type: MovementType; reason: string | null; reference_type: string | null; reference_id: string | null; reference_number: string | null; store_id: string | null; warehouse_id: string | null; notes: string | null; edited_by: string | null; created_at: string; }
export interface InventoryWithProduct extends CentralInventory { product_name: string; product_sku: string | null; available_stock: number; stock_status: 'ok' | 'low' | 'out'; backorder?: boolean; allow_backorder?: boolean; }
export type OrderStatus = 'pending_payment' | 'paid' | 'confirmed' | 'picking' | 'picked' | 'packing' | 'packed' | 'ready_to_ship' | 'shipment_booked' | 'collected' | 'shipped' | 'at_local_depot' | 'out_for_delivery' | 'delivered' | 'completed' | 'cancelled' | 'refunded' | 'delivery_attempted' | 'ready_for_collection' | 'delivery_rescheduled' | 'returned' | 'failed';
export type WarehouseStatus = 'pending' | 'picking' | 'picked' | 'packing' | 'packed' | 'ready_to_ship' | 'dispatched'; export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded'; export type PaymentMethod = 'paypal' | 'card' | 'wallet' | 'cod' | 'bank_transfer' | 'other'; export type InventorySyncStatus = 'pending' | 'synced' | 'failed' | 'partial'; export type SyncState = 'idle' | 'syncing' | 'synced' | 'error' | 'pending' | 'failed'; export type FulfillmentStatus = OrderStatus;
export interface Order { id: string; user_id: string | null; store_id: string | null; order_number: string; customer_name: string; customer_email: string; customer_phone: string; delivery_address: string; delivery_city: string; delivery_postcode: string; subtotal: number; delivery_fee: number; total: number; payment_method: PaymentMethod; payment_status: PaymentStatus; order_status: OrderStatus; warehouse_status: WarehouseStatus; fulfillment_status?: FulfillmentStatus; packed_at?: string | null; ready_to_ship_at?: string | null; fulfillment_notes?: string | null; payment_reference: string | null; notes: string | null; inventory_synced_at: string | null; inventory_sync_status: InventorySyncStatus; product_cost_total: number; product_cost_net: number; packing_cost_net: number; shipping_cost_net: number; gateway_fee_net: number; total_cost_net: number; platform_fee: number; total_revenue: number; gross_profit: number; profit_margin: number; cost_per_kg: number | null; picking_started_at?: string | null; picking_completed_at?: string | null; picked_by_user?: string | null; packed_by_user?: string | null; picking_duration?: number | null; locked_by?: string | null; locked_at?: string | null; created_at: string; updated_at: string; }
export interface OrderItem { id: string; order_id: string; product_id: string | null; product_name: string; product_image: string | null; quantity: number; unit_price: number; total_price: number; cost_price: number | null; brand: string | null; weight: number | null; unit: string | null; sku: string | null; supplier_sku?: string | null; picked_quantity: number; verified_quantity: number; required_quantity: number; last_scanned_gtin: string | null; picked_at: string | null; picked_by: string | null; skip_reason: string | null; created_at: string; }
export interface OrderWithItems extends Order { items: OrderItem[]; }
export interface OrderStatusHistory { id: string; order_id: string; old_status: OrderStatus | null; new_status: OrderStatus; inventory_action: 'reserve' | 'commit' | 'release' | 'return' | 'none' | null; inventory_action_completed: boolean; notes: string | null; created_at: string; created_by: string | null; }
export interface CreateOrderData { store_id: string; customer_name: string; customer_email: string; customer_phone: string; delivery_address: string; delivery_city: string; delivery_postcode: string; payment_method: PaymentMethod; notes?: string; items: { product_id: string; product_name: string; product_image?: string; quantity: number; unit_price: number; }[]; }
export interface InventoryValidationResult { valid: boolean; errors: { product_id: string; product_name: string; requested: number; available: number; message: string; }[]; backorder_items: { product_id: string; product_name: string; requested: number; available: number; }[]; }
export type ShipmentStatus = 'not_shipped' | 'ready_to_ship' | 'label_created' | 'collected' | 'in_transit' | 'arrived_at_depot' | 'at_local_depot' | 'out_for_delivery' | 'delivered' | 'failed' | 'cancelled' | 'returned' | 'delivery_attempted' | 'ready_for_collection' | 'delivery_rescheduled'; export type ServiceType = 'standard' | 'express' | 'priority'; export type Carrier = 'dhl';
export interface Shipment { id: string; order_id: string | null; shipment_number: string | null; carrier: Carrier; service_type: ServiceType; tracking_number: string | null; tracking_url?: string | null; label_url: string | null; status: ShipmentStatus; shipping_cost: number; weight_grams: number; sender_name: string; sender_address: string; sender_city: string; sender_postcode: string; sender_phone: string; recipient_name: string; recipient_company_name: string | null; recipient_address: string; recipient_city: string; recipient_postcode: string; recipient_phone: string; recipient_email: string | null; carrier_reference: string | null; estimated_delivery: string | null; actual_delivery: string | null; booked_at?: string | null; label_printed: boolean; error_message: string | null; metadata: Record<string, any>; created_at: string; updated_at: string; }
export interface ShipmentSyncEvent { id: string; event_type: string; store_id: string; order_number: string; shipment_id: string; payload: any; status: 'pending' | 'processing' | 'completed' | 'failed' | 'retry'; retry_count: number; error_message?: string; processed_at?: string; created_at: string; }
export interface ShipmentEvent { id: string; shipment_id: string; status: string; location: string | null; description: string; event_time: string; metadata: Record<string, any>; created_at: string; }
export interface ShippingRateCache { id: string; carrier: Carrier; service_type: ServiceType; from_postcode: string; to_postcode: string; weight_grams: number; cost: number; expires_at: string; created_at: string; }
export interface SenderProfile { id: string; name: string; company_name: string; contact_name: string; address_line1: string; address_line2: string | null; city: string; postcode: string; country: string; phone: string; email: string; is_default: boolean; site: string | null; created_at: string; updated_at: string; }
export interface CreateShipmentRequest { order_id: string; carrier?: Carrier; service_type?: ServiceType; weight_grams: number; sender_profile_id?: string; recipient_name: string; recipient_company_name?: string; recipient_address: string; recipient_city: string; recipient_postcode: string; recipient_phone: string; recipient_email?: string; }
export interface ShippingRate { carrier: Carrier; service_type: ServiceType; cost: number; estimated_days: number; currency: string; }
export interface ShipmentWithOrder extends Shipment { order?: Order; }
export interface ShippingDashboardStats { total_shipments: number; not_shipped: number; in_transit: number; delivered: number; failed: number; total_cost: number; average_cost: number; }
export type HandlingMode = 'AI' | 'AI_DRAFT' | 'HUMAN'; export type ConversationStatus = 'open' | 'waiting' | 'human' | 'closed'; export type MessageDirection = 'inbound' | 'outbound'; export type MessageType = 'text' | 'image' | 'document' | 'audio' | 'interactive' | 'template'; export type MessageStatus = 'received' | 'sent' | 'delivered' | 'read' | 'failed';
export interface WhatsAppContact { id: string; store_id: string | null; customer_id: string | null; phone_number: string; whatsapp_user_id: string | null; display_name: string | null; language: string | null; opted_in: boolean; last_message_at: string | null; created_at: string; updated_at: string; }
export interface WhatsAppConversation { id: string; store_id: string | null; contact_id: string; status: ConversationStatus; handling_mode: HandlingMode; ai_enabled: boolean; assigned_to: string | null; assigned_agent_id: string | null; last_message_at: string | null; closed_at: string | null; created_at: string; updated_at: string; contact?: WhatsAppContact; }
export interface WhatsAppMessage { id: string; conversation_id: string; wa_message_id: string | null; direction: MessageDirection; message_type: MessageType; message_text: string | null; media_url: string | null; sender_phone: string | null; status: MessageStatus; ai_generated: boolean; ai_model: string | null; created_at: string; updated_at: string; }
export type TicketCategory = 'refund' | 'missing_order' | 'wrong_item' | 'damaged_item' | 'delivery_issue' | 'payment_issue' | 'complaint' | 'account_issue' | 'other'; export type TicketPriority = 'low' | 'medium' | 'high' | 'urgent'; export type TicketStatus = 'open' | 'assigned' | 'in_progress' | 'waiting_customer' | 'waiting_internal' | 'resolved' | 'closed';
export interface SupportTicket { id: string; store_id: string; customer_id?: string | null; conversation_id?: string | null; category: TicketCategory; priority: TicketPriority; status: TicketStatus; ai_summary?: string | null; description?: string | null; subject?: string | null; contact_id?: string | null; resolution?: string | null; created_at: string; updated_at: string; resolved_at?: string | null; }
export interface ProductSupplierMapping { id: string; product_id: string; supplier_id: string; supplier_sku?: string | null; supplier_product_name?: string | null; supplier_barcode?: string | null; cost_price?: number; lead_time_days?: number; minimum_order_qty?: number; is_preferred?: boolean; is_active?: boolean; created_at?: string; updated_at?: string; }
export interface PriceSuggestion { id: string; product_id: string; store_id?: string | null; current_price: number; suggested_price: number; cost_price?: number | null; decision_reason?: string | null; competitive_target_price?: number | null; required_profit_price?: number | null; final_price?: number | null; }
export interface BackorderItem { id: string; order_id: string; product_id: string; quantity_ordered: number; quantity_fulfilled: number; status: 'pending' | 'partial' | 'fulfilled' | 'cancelled'; priority_score: number; expected_fulfillment_date: string | null; assigned_po_id: string | null; notes: string | null; created_at: string; updated_at: string; product?: Product; order?: Order; }
