export type CampaignPlatform = 'google_ads' | 'meta_ads' | 'whatsapp' | 'email' | 'multi' | 'social' | string;
export type CampaignType = 'traffic' | 'conversions' | 'retargeting' | 'awareness' | 'engagement';
export type CampaignStatus = 'draft' | 'active' | 'paused' | 'completed' | 'archived' | 'deleted';
export interface MarketingProvider { id: string; display_name: string; category: 'advertising' | 'social' | 'search' | 'commerce' | 'messaging' | 'email' | 'analytics'; icon?: string; auth_method: 'oauth2' | 'api_key' | 'none'; capabilities: string[]; is_active: boolean; is_verified: boolean; setup_instructions?: string; }
export interface MarketingConnection { id: string; store_id: string; provider_id: string; external_account_id?: string; external_account_name?: string; status: 'not_connected' | 'connecting' | 'connected' | 'syncing' | 'healthy' | 'warning' | 'error' | 'disconnected'; health_score: number; last_sync_at?: string; last_error?: string; config: any; created_at: string; updated_at: string; provider?: MarketingProvider; }
export interface MarketingAsset { id: string; connection_id: string; store_id: string; asset_type: 'ad_account' | 'facebook_page' | 'instagram_profile' | 'pixel' | 'catalog' | 'merchant_center' | 'ga4_property'; external_id: string; name: string; is_assigned: boolean; status: string; metadata: any; created_at: string; updated_at: string; }
export interface Campaign { id: string; store_id: string; provider_id: string; external_campaign_id?: string; name: string; status: CampaignStatus; objective?: string; campaign_type?: string; platform?: CampaignPlatform; budget: number; budget_type: 'daily' | 'lifetime'; budget_amount: number; currency: string; start_date?: string; end_date?: string; targeting: any; creative_config: any; creative?: any; config?: any; metadata: any; created_at: string; updated_at: string; }
export interface MarketingMetric { id: string; store_id: string; campaign_id?: string; provider_id: string; external_id?: string; date: string; spend: number; impressions: number; clicks: number; conversions: number; conversion_value: number; reach: number; metadata: any; }
export interface MarketingEvent { id: string; store_id: string; session_id: string; customer_id?: string; order_id?: string; event_type: string; event_source: 'web' | 'app' | 'server'; url?: string; referrer?: string; utm_source?: string; utm_medium?: string; utm_campaign?: string; utm_content?: string; utm_term?: string; click_id?: string; metadata: any; timestamp: string; }
export interface MarketingSyncJob { id: string; store_id: string; connection_id?: string; provider_id: string; job_type: 'initial_sync' | 'incremental_metrics' | 'catalog_sync' | 'audience_sync'; status: 'queued' | 'running' | 'completed' | 'partial' | 'failed'; progress: number; error_message?: string; started_at?: string; completed_at?: string; metadata: any; created_at: string; }
export interface MarketingCreative { id: string; store_id: string; name: string; file_url: string; file_type: 'image' | 'video' | 'carousel'; dimensions?: string; size_bytes?: number; product_id?: string; external_asset_id?: string; provider_id?: string; status: string; metadata: any; created_at: string; updated_at: string; }
export interface MarketingAudience { id: string; store_id: string; name: string; description?: string; segment_id?: string; rules: any; size_count: number; status: string; created_at: string; updated_at: string; }
export interface MarketingSegment { id: string; store_id: string; name: string; description?: string; rules: any; member_count: number; is_active: boolean; last_calculated_at?: string; created_at: string; updated_at: string; }
export interface Promotion { id: string; store_id?: string; name: string; description?: string; status: string; coupon_code?: string; discount_type?: string; discount_value?: number; usage_limit?: number; created_at: string; }
export interface MarketingInsight { id: string; store_id: string; title: string; description: string; priority: 'low' | 'medium' | 'high'; status: 'new' | 'dismissed' | 'applied'; created_at: string; }
