'use client';

import { useCallback, useEffect, useState } from 'react';
import { useStore } from '@/lib/store/useStore';
import { supabase } from '@/lib/supabase';

const input = 'w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-white outline-none focus:border-blue-500';

export default function CreativeLibraryLiveClient() {
  const { selectedStore } = useStore();
  const storeId = selectedStore?.id || '';
  const [assets,setAssets]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState({name:'',fileUrl:'',fileType:'image',productId:''});

  const load=useCallback(async()=>{if(!storeId){setAssets([]);setLoading(false);return;}setLoading(true);setError('');const [a,p]=await Promise.all([supabase.from('marketing_creatives').select('id,name,file_url,file_type,dimensions,size_bytes,product_id,external_asset_id,status,created_at').eq('store_id',storeId).order('created_at',{ascending:false}),supabase.from('products').select('id,name,sku').eq('is_active',true).eq('is_deleted',false).order('name').limit(200)]);if(a.error)setError(a.error.message);else setAssets(a.data||[]);if(p.error)setError(p.error.message);else setProducts(p.data||[]);setLoading(false);},[storeId]);
  useEffect(()=>{load();},[load]);
  const add=async()=>{if(!storeId)return setError('Select a store first.');if(!form.name.trim()||!form.fileUrl.trim())return setError('Name and asset URL are required.');setSaving(true);setError('');const {error:e}=await supabase.from('marketing_creatives').insert({store_id:storeId,name:form.name.trim(),file_url:form.fileUrl.trim(),file_type:form.fileType,product_id:form.productId||null,status:'active'});if(e)setError(e.message);else{setForm({name:'',fileUrl:'',fileType:'image',productId:''});await load();}setSaving(false);};
  const remove=async(id:string)=>{if(!confirm('Delete this creative?'))return;const {error:e}=await supabase.from('marketing_creatives').delete().eq('id',id).eq('store_id',storeId);if(e)setError(e.message);else await load();};
  const productName=(id:string)=>products.find(p=>p.id===id)?.name||'—';
  return <div className="p-6 space-y-6 max-w-7xl mx-auto text-white"><div className="flex justify-between flex-wrap gap-4"><div><h1 className="text-3xl font-black">Creative Library</h1><p className="text-slate-400">Live marketing creatives stored against the selected store.</p></div><button onClick={load} className="px-4 py-2 rounded-lg border border-slate-700">Refresh</button></div>{error&&<div className="p-3 rounded-lg bg-red-500/10 border border-red-500/30 text-red-300">{error}</div>}{!storeId&&<div className="p-4 rounded-xl border border-amber-500/30 bg-amber-500/10 text-amber-200">Select a store to manage its creative library.</div>}{storeId&&<div className="grid lg:grid-cols-[360px_1fr] gap-6"><div className="rounded-2xl border border-slate-800 bg-slate-950 p-5 space-y-4"><h2 className="font-bold">Add creative</h2><input className={input} placeholder="Asset name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={input} placeholder="Public/storage asset URL" value={form.fileUrl} onChange={e=>setForm({...form,fileUrl:e.target.value})}/><select className={input} value={form.fileType} onChange={e=>setForm({...form,fileType:e.target.value})}><option value="image">Image</option><option value="video">Video</option><option value="carousel">Carousel</option></select><select className={input} value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}><option value="">No product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} {p.sku?`(${p.sku})`:''}</option>)}</select><button disabled={saving} onClick={add} className="w-full px-4 py-2 rounded-lg bg-emerald-600 font-bold">{saving?'Saving…':'Save creative'}</button></div><div className="rounded-2xl border border-slate-800 bg-slate-950 overflow-hidden"><div className="p-4 border-b border-slate-800 font-bold">Live assets ({assets.length})</div>{loading?<div className="p-8 text-slate-400">Loading…</div>:assets.length===0?<div className="p-10 text-center text-slate-500">No creatives stored for this store.</div>:<div className="grid md:grid-cols-2 gap-4 p-4">{assets.map(a=><div key={a.id} className="rounded-xl border border-slate-800 overflow-hidden"><div className="aspect-video bg-slate-900 flex items-center justify-center">{a.file_type==='image'?<img src={a.file_url} alt={a.name} className="w-full h-full object-cover" onError={e=>{(e.currentTarget as HTMLImageElement).style.display='none'}}/>:<span className="text-4xl">{a.file_type==='video'?'🎬':'🧩'}</span>}</div><div className="p-4 space-y-2"><div className="font-bold">{a.name}</div><div className="text-xs text-slate-500">{a.file_type} · {productName(a.product_id)}</div><div className="flex justify-between items-center"><a href={a.file_url} target="_blank" rel="noreferrer" className="text-cyan-400 text-xs">Open asset</a><button onClick={()=>remove(a.id)} className="text-xs text-red-300">Delete</button></div></div></div>)}</div>}</div></div>}</div>;
}
