import Link from 'next/link';
import type { Metadata } from 'next';
export const metadata:Metadata={title:'Tax and government integration roadmap | CentralHub',description:'Status of VAT, Corporation Tax, PAYE, Business Rates, Customs and company filing integrations. No live tax filing or government payment is enabled.'};
const modules=[
 {title:'Making Tax Digital for VAT',status:'In development · sandbox application diagnostic',text:'Internal VAT management views and a protected application-only HMRC sandbox Hello World diagnostic exist. Taxpayer OAuth, VAT obligations retrieval, complete returns workflow, required fraud-prevention information and production filing are not verified or enabled.'},
 {title:'Corporation Tax · CT600',status:'Planned',text:'Accounting-period reports, taxable-profit adjustments, CT600 and associated accounts formats would require their own submission implementation and test access. No live return submission is available.'},
 {title:'PAYE · employer RTI',status:'Planned',text:'Payroll records, employee deductions and FPS/EPS submissions would require separate employer permissions and the relevant HMRC RTI testing and submission process. No live employer reporting is available.'},
 {title:'Business Rates',status:'Planned · council-specific',text:'Property billing, rateable-value references, reliefs, payment reminders and reconciliation may be supported. Direct access and payment depend on the relevant local authority; this is not a universal HMRC API.'},
 {title:'Customs Duty · Import VAT',status:'Planned',text:'EORI information, commodity codes, import/export records, declarations and duty reconciliation would require relevant Customs Declaration Service processes and authorisations. A declaration interface alone does not authorise an actual customs payment.'},
 {title:'Companies House filings',status:'Read-only sandbox diagnostic available when configured',text:'A protected test-company lookup can be run with configured sandbox credentials. It does not authorise live accounts filings or company document submissions.'},
] as const;
export default function TaxIntegrations(){return <main className="min-h-screen bg-[#07111f] px-5 py-10 text-slate-100 sm:py-16"><div className="mx-auto max-w-4xl"><Link href="/" className="text-xl font-black text-cyan-300">CentralHub</Link><p className="mt-12 text-xs font-bold uppercase tracking-[0.2em] text-cyan-300">Tax &amp; government integration status</p><h1 className="mt-3 text-4xl font-black">A clear roadmap for each service</h1><p className="mt-5 text-sm leading-7 text-slate-300">Existing finance screens do not represent HMRC production approval. Each government or council service has its own account permissions, test arrangements and rules. No live tax filing, customs declaration or government payment is enabled through this roadmap.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{modules.map(m=><section key={m.title} className="rounded-2xl border border-white/10 bg-[#102338] p-6"><h2 className="text-lg font-bold">{m.title}</h2><p className="mt-3 text-xs font-bold uppercase tracking-wide text-cyan-300">{m.status}</p><p className="mt-3 text-sm leading-7 text-slate-300">{m.text}</p></section>)}</div><section className="mt-8 rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-6"><h2 className="text-lg font-bold">Before any service goes live</h2><p className="mt-3 text-sm leading-7 text-slate-300">Verify official API availability, sandbox tests, credentials, production access, secure storage, tenant permissions, applicable privacy notices and explicit authorised-user approval for the specific submission or payment. A general acceptance of website terms is not government account authorisation.</p><p className="mt-3 text-sm text-slate-300">See our <Link href="/privacy" className="text-cyan-300 underline">privacy notice</Link> and <Link href="/terms" className="text-cyan-300 underline">website terms</Link>.</p></section><Link href="/" className="mt-8 inline-block font-bold text-cyan-300 underline">Return to homepage</Link></div></main>}
