-- Unified Meta social customer-care channels (Facebook + Instagram), additive to existing WhatsApp tables.
create table if not exists public.customer_care_channels (
 id uuid primary key default gen_random_uuid(), store_id uuid not null references public.stores(id) on delete cascade,
 channel_type text not null check(channel_type in('whatsapp','instagram','facebook')), provider text not null default 'meta' check(provider in('meta','interakt')),
 external_account_id text not null, page_id text, instagram_business_account_id text, display_name text,
 status text not null default 'disconnected' check(status in('disconnected','configured','active','error')),
 connection_id uuid references public.marketing_connections(id) on delete set null, provider_config_id uuid references public.marketing_provider_configs(id) on delete set null,
 encrypted_access_token text, token_expires_at timestamptz, last_webhook_at timestamptz, last_error text, metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(store_id,channel_type,provider,external_account_id));
create table if not exists public.customer_social_identities(id uuid primary key default gen_random_uuid(),store_id uuid not null references public.stores(id) on delete cascade,channel_id uuid not null references public.customer_care_channels(id) on delete cascade,customer_id uuid references public.customers(id) on delete set null,channel_type text not null check(channel_type in('instagram','facebook')),external_user_id text not null,display_name text,username text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(channel_id,external_user_id));
alter table public.whatsapp_conversations add column if not exists channel_id uuid references public.customer_care_channels(id) on delete set null;
alter table public.whatsapp_conversations add column if not exists channel_type text not null default 'whatsapp' check(channel_type in('whatsapp','instagram','facebook'));
alter table public.whatsapp_conversations add column if not exists external_thread_id text; alter table public.whatsapp_conversations add column if not exists external_contact_id text;
alter table public.whatsapp_messages add column if not exists channel_type text not null default 'whatsapp' check(channel_type in('whatsapp','instagram','facebook')); alter table public.whatsapp_messages add column if not exists external_message_id text;
create table if not exists public.meta_social_webhook_events(id uuid primary key default gen_random_uuid(),event_id text not null,channel_type text not null check(channel_type in('instagram','facebook')),provider text not null default 'meta',payload jsonb not null,processing_status text not null default 'received',processed_at timestamptz,error_message text,created_at timestamptz not null default now(),unique(provider,event_id));
create index if not exists idx_customer_care_channels_store_type on public.customer_care_channels(store_id,channel_type,status); create index if not exists idx_customer_care_channels_external_lookup on public.customer_care_channels(channel_type,external_account_id,status); create index if not exists idx_customer_care_channels_connection_id on public.customer_care_channels(connection_id) where connection_id is not null; create index if not exists idx_customer_care_channels_provider_config_id on public.customer_care_channels(provider_config_id) where provider_config_id is not null; create index if not exists idx_social_identities_store_channel on public.customer_social_identities(store_id,channel_id); create index if not exists idx_customer_social_identities_customer_id on public.customer_social_identities(customer_id) where customer_id is not null; create index if not exists idx_whatsapp_conversations_channel_id on public.whatsapp_conversations(channel_id) where channel_id is not null; create unique index if not exists idx_whatsapp_messages_external_message_unique on public.whatsapp_messages(channel_type,external_message_id) where external_message_id is not null; create index if not exists idx_meta_social_webhook_status on public.meta_social_webhook_events(processing_status,created_at desc);
alter table public.customer_care_channels enable row level security; alter table public.customer_social_identities enable row level security; alter table public.meta_social_webhook_events enable row level security;
do $$ begin if not exists(select 1 from pg_policies where schemaname='public' and tablename='customer_care_channels' and policyname='centralhub_admin_only') then create policy centralhub_admin_only on public.customer_care_channels for all using(is_admin()) with check(is_admin()); end if; if not exists(select 1 from pg_policies where schemaname='public' and tablename='customer_social_identities' and policyname='centralhub_admin_only') then create policy centralhub_admin_only on public.customer_social_identities for all using(is_admin()) with check(is_admin()); end if; if not exists(select 1 from pg_policies where schemaname='public' and tablename='meta_social_webhook_events' and policyname='centralhub_admin_only') then create policy centralhub_admin_only on public.meta_social_webhook_events for all using(is_admin()) with check(is_admin()); end if; end $$;
insert into public.customer_care_channels(store_id,channel_type,provider,external_account_id,display_name,status,metadata) select wc.store_id,'whatsapp','meta',coalesce(wc.phone_number_id,wc.id::text),coalesce(wc.business_name,wc.display_phone_number,'WhatsApp'),case when wc.status='active' then 'active' else 'configured' end,jsonb_build_object('waba_id',wc.waba_id,'phone_number_id',wc.phone_number_id,'display_phone_number',wc.display_phone_number,'source','whatsapp_channels') from public.whatsapp_channels wc where wc.store_id is not null on conflict(store_id,channel_type,provider,external_account_id) do update set display_name=excluded.display_name,status=excluded.status,metadata=excluded.metadata,updated_at=now();
