-- Purchase procurement engine v2. Live database implementation.
-- Source of truth remains products + product_suppliers + supplier price-list snapshots.
CREATE OR REPLACE FUNCTION public.get_supplier_offers_for_product(p_product_id uuid) RETURNS TABLE(supplier_id uuid,supplier_name text,product_id uuid,supplier_product_id uuid,supplier_sku text,supplier_barcode text,supplier_product_name text,unit_cost numeric,pack_size integer,case_quantity integer,moq integer,lead_time_days integer,vat_rate numeric,source text,valid_from date,valid_until date,availability_status text,is_preferred boolean) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $fn$
WITH candidates AS (
 SELECT ps.supplier_id,s.name AS sname,p.id AS pid,ps.id AS spid,COALESCE(spl.supplier_sku,ps.supplier_sku) AS ss,COALESCE(spl.supplier_barcode,ps.supplier_barcode,p.gtin) AS sb,COALESCE(spl.supplier_product_name,ps.supplier_product_name,p.name) AS spn,
 COALESCE(spl.unit_price,CASE WHEN COALESCE(spl.case_price,0)>0 THEN spl.case_price/GREATEST(COALESCE(spl.case_quantity,1),1) ELSE spl.cost_price END,ps.cost_price) AS uc,
 GREATEST(COALESCE(spl.pack_size,ps.pack_size,1),1) AS pk,GREATEST(COALESCE(spl.case_quantity,ps.case_quantity,1),1) AS cq,GREATEST(COALESCE(spl.moq,ps.minimum_order_qty,1),1) AS mq,COALESCE(spl.lead_time_days,ps.lead_time_days,7) AS ltd,COALESCE(spl.vat_rate,ps.vat_rate,0) AS vr,
 CASE WHEN spl.id IS NULL THEN 'product_supplier' ELSE 'price_list' END AS src,spl.valid_from AS vf,spl.valid_until AS vu,COALESCE(spl.availability_status,'available') AS av,COALESCE(ps.is_preferred,false) AS pref,
 row_number() OVER(PARTITION BY ps.supplier_id ORDER BY CASE WHEN spl.id IS NULL THEN 1 ELSE 0 END,spl.valid_from DESC NULLS LAST,spl.created_at DESC NULLS LAST) AS rn
 FROM public.products p JOIN public.product_suppliers ps ON ps.product_id=p.id AND COALESCE(ps.is_active,true) JOIN public.suppliers s ON s.id=ps.supplier_id AND COALESCE(s.is_active,true)
 LEFT JOIN public.supplier_price_lists spl ON spl.product_id=p.id AND spl.supplier_id=ps.supplier_id AND COALESCE(spl.is_active,true) AND (spl.valid_from IS NULL OR spl.valid_from<=CURRENT_DATE) AND (spl.valid_until IS NULL OR spl.valid_until>=CURRENT_DATE)
 WHERE p.id=p_product_id AND COALESCE(spl.availability_status,'available') NOT IN('failed','unavailable')
)
SELECT supplier_id,sname,pid,spid,ss,sb,spn,uc,pk,cq,mq,ltd,vr,src,vf,vu,av,pref FROM candidates WHERE rn=1 AND uc>0 ORDER BY uc,pref DESC,ltd;
$fn$;
CREATE OR REPLACE FUNCTION public.get_purchase_recommendations(p_days integer DEFAULT 30,p_target_cover_days integer DEFAULT 14) RETURNS TABLE(product_id uuid,product_name text,sku text,gtin text,stock_quantity integer,reserved_quantity integer,available_quantity integer,units_sold_period integer,avg_daily_units numeric,recent_7d_units numeric,recent_30d_units numeric,expected_daily_units numeric,days_of_cover numeric,incoming_quantity integer,recommended_quantity integer,best_supplier_id uuid,best_supplier_name text,best_unit_cost numeric,supplier_count integer,recommendation_reason text) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $fn$
WITH sales AS (SELECT oi.product_id AS sid,COALESCE(SUM(CASE WHEN o.created_at>=now()-interval '7 days' THEN oi.quantity ELSE 0 END),0)::int AS r7,COALESCE(SUM(oi.quantity),0)::int AS rp FROM public.order_items oi JOIN public.orders o ON o.id=oi.order_id WHERE COALESCE(o.is_deleted,false)=false AND o.payment_status='paid' AND COALESCE(o.order_status,'') NOT IN('cancelled','refunded') AND o.created_at>=now()-make_interval(days=>GREATEST(p_days,7)) GROUP BY oi.product_id), incoming AS (SELECT poi.product_id AS iid,COALESCE(SUM(GREATEST(poi.quantity_ordered-poi.quantity_received,0)),0)::int AS iq FROM public.purchase_order_items poi JOIN public.purchase_orders po ON po.id=poi.purchase_order_id WHERE po.status IN('draft','sent','confirmed','partially_received') GROUP BY poi.product_id), base AS (SELECT p.id AS pid,p.name AS pname,p.sku,p.gtin,COALESCE(ci.stock_quantity,p.stock,0) AS sq,COALESCE(ci.reserved_quantity,0) AS rq,GREATEST(COALESCE(ci.stock_quantity,p.stock,0)-COALESCE(ci.reserved_quantity,0),0) AS aq,COALESCE(s.rp,0) AS rp,(COALESCE(s.rp,0)::numeric/GREATEST(p_days,1)) AS ad,(COALESCE(s.r7,0)::numeric/7) AS r7d,(COALESCE(s.rp,0)::numeric/GREATEST(p_days,1)) AS r30d,GREATEST(COALESCE(s.r7,0)::numeric/7,COALESCE(s.rp,0)::numeric/GREATEST(p_days,1)) AS ed,COALESCE(i.iq,0) AS iq FROM public.products p LEFT JOIN public.central_inventory ci ON ci.product_id=p.id LEFT JOIN sales s ON s.sid=p.id LEFT JOIN incoming i ON i.iid=p.id WHERE COALESCE(p.is_deleted,false)=false AND COALESCE(p.is_active,true)=true), rec AS (SELECT b.*,CASE WHEN b.ed>0 THEN b.aq/b.ed END AS dc,GREATEST(CEIL((b.ed*p_target_cover_days)+b.ed*7-b.aq-b.iq),0)::int AS rawq FROM base b), best AS (SELECT r.pid,o.*,row_number() OVER(PARTITION BY r.pid ORDER BY o.unit_cost,o.is_preferred DESC,o.lead_time_days) AS rn FROM rec r CROSS JOIN LATERAL public.get_supplier_offers_for_product(r.pid) o) SELECT r.pid,r.pname,r.sku,r.gtin,r.sq,r.rq,r.aq,r.rp,round(r.ad,2),round(r.r7d,2),round(r.r30d,2),round(r.ed,2),round(r.dc,2),r.iq,CASE WHEN r.rawq<=0 THEN 0 WHEN b.supplier_id IS NULL THEN r.rawq ELSE CEIL(GREATEST(r.rawq,b.moq)::numeric/GREATEST(b.case_quantity,1))*GREATEST(b.case_quantity,1) END::int,b.supplier_id,b.supplier_name,b.unit_cost,(SELECT count(*) FROM public.get_supplier_offers_for_product(r.pid))::int,CASE WHEN r.rawq<=0 THEN 'Stock and incoming supply cover expected demand.' WHEN b.supplier_id IS NULL THEN 'Replenishment required but no valid active supplier offer is available.' ELSE 'Calculated from sales flow, available stock, incoming PO quantity, target cover, supplier MOQ and case quantity.' END FROM rec r LEFT JOIN best b ON b.pid=r.pid AND b.rn=1;
$fn$;
CREATE OR REPLACE FUNCTION public.create_purchase_order_from_items(p_supplier_id uuid,p_items jsonb,p_notes text DEFAULT NULL,p_source_type text DEFAULT 'replenishment') RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $fn$
DECLARE v_po uuid;v_num text;x jsonb;pid uuid;qty int;offer record;
BEGIN IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin authorization required'; END IF; IF p_supplier_id IS NULL OR jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 THEN RAISE EXCEPTION 'Supplier and items are required'; END IF; v_num:='PO-'||to_char(now(),'YYYYMMDD-HH24MISS')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6)); INSERT INTO public.purchase_orders(po_number,supplier_id,status,order_date,total_cost,currency,notes,created_by,source_type) VALUES(v_num,p_supplier_id,'draft',CURRENT_DATE,0,'GBP',p_notes,auth.uid(),COALESCE(p_source_type,'manual')) RETURNING id INTO v_po; FOR x IN SELECT value FROM jsonb_array_elements(p_items) LOOP pid=(x->>'product_id')::uuid;qty=GREATEST(COALESCE((x->>'quantity')::int,0),0);IF qty>0 THEN SELECT * INTO offer FROM public.get_supplier_offers_for_product(pid) WHERE supplier_id=p_supplier_id LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'No valid offer for product % from supplier %',pid,p_supplier_id;END IF;INSERT INTO public.purchase_order_items(purchase_order_id,product_id,supplier_product_name,supplier_sku,quantity_ordered,quantity_received,unit_cost,source_reason,forecast_quantity,gtin,supplier_product_id,pack_size,case_quantity,unit_cost_ex_vat,supplier_offer_source,expected_quantity) VALUES(v_po,pid,offer.supplier_product_name,offer.supplier_sku,qty,0,offer.unit_cost,'FAST_MOVING',qty,offer.supplier_barcode,offer.supplier_product_id,offer.pack_size,offer.case_quantity,offer.unit_cost,offer.source,qty);END IF;END LOOP;IF NOT EXISTS(SELECT 1 FROM public.purchase_order_items WHERE purchase_order_id=v_po) THEN DELETE FROM public.purchase_orders WHERE id=v_po;RAISE EXCEPTION 'No valid purchase items supplied';END IF;UPDATE public.purchase_orders SET total_cost=(SELECT COALESCE(sum(total),0) FROM public.purchase_order_items WHERE purchase_order_id=v_po),supplier_selection_reason='Supplier selected from current valid offer using normalized unit cost, MOQ/case constraints and lead time.',source_type=COALESCE(p_source_type,'manual') WHERE id=v_po;RETURN v_po;END;
$fn$;