-- Purchase receiving/reconciliation additions already applied to live Supabase.
-- This migration records the schema contract in Git for future environments.
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS price_list_history_id uuid REFERENCES public.supplier_price_list_history(id) ON DELETE SET NULL;
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS supplier_barcode text;
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS unit_price numeric(12,4);
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS case_price numeric(12,4);
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS pack_size integer NOT NULL DEFAULT 1;
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS case_quantity integer NOT NULL DEFAULT 1;
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS vat_rate numeric(6,3) NOT NULL DEFAULT 0;
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS availability_status text NOT NULL DEFAULT 'available';
ALTER TABLE public.supplier_price_lists ADD COLUMN IF NOT EXISTS source_file_name text;
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS source_draft_id uuid REFERENCES public.po_drafts(id) ON DELETE SET NULL;
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES auth.users(id);
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS supplier_selection_reason text;
ALTER TABLE public.purchase_orders ADD COLUMN IF NOT EXISTS source_type text NOT NULL DEFAULT 'manual';
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS gtin text;
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS supplier_product_id uuid REFERENCES public.product_suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS pack_size integer NOT NULL DEFAULT 1;
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS case_quantity integer NOT NULL DEFAULT 1;
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS unit_cost_ex_vat numeric(12,4);
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS supplier_offer_source text;
ALTER TABLE public.purchase_order_items ADD COLUMN IF NOT EXISTS expected_quantity integer;
ALTER TABLE public.supplier_invoices ADD COLUMN IF NOT EXISTS purchase_order_id uuid REFERENCES public.purchase_orders(id) ON DELETE SET NULL;
ALTER TABLE public.supplier_invoices ADD COLUMN IF NOT EXISTS invoice_file_name text;
ALTER TABLE public.supplier_invoices ADD COLUMN IF NOT EXISTS uploaded_at timestamptz;
ALTER TABLE public.supplier_invoices ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES auth.users(id);
ALTER TABLE public.supplier_invoice_items ADD COLUMN IF NOT EXISTS purchase_order_item_id uuid REFERENCES public.purchase_order_items(id) ON DELETE SET NULL;
ALTER TABLE public.supplier_invoice_items ADD COLUMN IF NOT EXISTS gtin text;
ALTER TABLE public.supplier_invoice_items ADD COLUMN IF NOT EXISTS quantity_invoiced integer;
ALTER TABLE public.supplier_invoice_items ADD COLUMN IF NOT EXISTS variance_quantity integer NOT NULL DEFAULT 0;
ALTER TABLE public.supplier_invoice_items ADD COLUMN IF NOT EXISTS variance_unit_cost numeric(12,4) NOT NULL DEFAULT 0;
ALTER TABLE public.supplier_invoice_items ADD COLUMN IF NOT EXISTS variance_total numeric(12,4) NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS public.purchase_receipts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),purchase_order_id uuid NOT NULL REFERENCES public.purchase_orders(id) ON DELETE RESTRICT,supplier_id uuid NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,supplier_invoice_id uuid REFERENCES public.supplier_invoices(id) ON DELETE SET NULL,receipt_number text NOT NULL UNIQUE,received_at timestamptz NOT NULL DEFAULT now(),status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','received','verified','disputed','cancelled')),notes text,created_by uuid REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.purchase_receipt_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),receipt_id uuid NOT NULL REFERENCES public.purchase_receipts(id) ON DELETE CASCADE,purchase_order_item_id uuid NOT NULL REFERENCES public.purchase_order_items(id) ON DELETE RESTRICT,product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,gtin text,quantity_received integer NOT NULL CHECK(quantity_received>0),unit_cost numeric(12,4) NOT NULL DEFAULT 0,invoice_unit_cost numeric(12,4),quantity_variance integer NOT NULL DEFAULT 0,price_variance numeric(12,4) NOT NULL DEFAULT 0,notes text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.purchase_receipt_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),receipt_item_id uuid NOT NULL REFERENCES public.purchase_receipt_items(id) ON DELETE CASCADE,product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,batch_id text,expiry_date date NOT NULL,quantity integer NOT NULL CHECK(quantity>0),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.purchase_reconciliations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),purchase_order_id uuid NOT NULL REFERENCES public.purchase_orders(id) ON DELETE RESTRICT,supplier_invoice_id uuid REFERENCES public.supplier_invoices(id) ON DELETE SET NULL,purchase_receipt_id uuid REFERENCES public.purchase_receipts(id) ON DELETE SET NULL,status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','matched','discrepancy','resolved')),po_quantity integer NOT NULL DEFAULT 0,received_quantity integer NOT NULL DEFAULT 0,invoiced_quantity integer NOT NULL DEFAULT 0,po_total numeric(12,4) NOT NULL DEFAULT 0,received_total numeric(12,4) NOT NULL DEFAULT 0,invoice_total numeric(12,4) NOT NULL DEFAULT 0,quantity_variance integer NOT NULL DEFAULT 0,price_variance numeric(12,4) NOT NULL DEFAULT 0,total_variance numeric(12,4) NOT NULL DEFAULT 0,variance_details jsonb NOT NULL DEFAULT '[]'::jsonb,resolution_notes text,resolved_by uuid REFERENCES auth.users(id),resolved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_po ON public.purchase_receipts(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipt_items_po_item ON public.purchase_receipt_items(purchase_order_item_id);
CREATE INDEX IF NOT EXISTS idx_purchase_receipt_items_gtin ON public.purchase_receipt_items(gtin);
CREATE INDEX IF NOT EXISTS idx_purchase_receipt_batches_product_expiry ON public.purchase_receipt_batches(product_id,expiry_date);
CREATE INDEX IF NOT EXISTS idx_purchase_reconciliations_po ON public.purchase_reconciliations(purchase_order_id);
