-- NORA Live Action Mode
-- Visible, auditable computer-use sessions with human-in-the-loop questions and approvals.

create table if not exists public.nora_action_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  goal text not null,
  target_system text,
  target_url text,
  status text not null default 'planned' check (status in ('planned','running','waiting_input','waiting_approval','paused','completed','failed','cancelled')),
  risk_level text not null default 'low' check (risk_level in ('read_only','low','medium','high','critical')),
  current_step text,
  awaiting_input boolean not null default false,
  requires_approval boolean not null default false,
  approval_reason text,
  browser_session_id text,
  screenshot_url text,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nora_action_steps (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.nora_action_sessions(id) on delete cascade,
  sequence_no bigint generated by default as identity,
  action_type text not null,
  description text not null,
  selector_hint text,
  input_summary text,
  status text not null default 'planned' check (status in ('planned','running','completed','failed','skipped','waiting_input','waiting_approval')),
  requires_approval boolean not null default false,
  screenshot_url text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.nora_action_questions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.nora_action_sessions(id) on delete cascade,
  step_id uuid references public.nora_action_steps(id) on delete set null,
  question text not null,
  answer text,
  status text not null default 'pending' check (status in ('pending','answered','dismissed')),
  is_sensitive boolean not null default false,
  created_at timestamptz not null default now(),
  answered_at timestamptz
);

create index if not exists nora_action_sessions_user_status_idx on public.nora_action_sessions(user_id,status,updated_at desc);
create index if not exists nora_action_steps_session_seq_idx on public.nora_action_steps(session_id,sequence_no);
create index if not exists nora_action_questions_session_status_idx on public.nora_action_questions(session_id,status,created_at);

alter table public.nora_action_sessions enable row level security;
alter table public.nora_action_steps enable row level security;
alter table public.nora_action_questions enable row level security;

drop policy if exists "NORA action sessions admin only" on public.nora_action_sessions;
create policy "NORA action sessions admin only" on public.nora_action_sessions
for all to authenticated
using (public.is_admin())
with check (public.is_admin() and user_id = auth.uid());

drop policy if exists "NORA action steps admin only" on public.nora_action_steps;
create policy "NORA action steps admin only" on public.nora_action_steps
for all to authenticated
using (public.is_admin() and exists (
  select 1 from public.nora_action_sessions s where s.id = session_id and s.user_id = auth.uid()
))
with check (public.is_admin() and exists (
  select 1 from public.nora_action_sessions s where s.id = session_id and s.user_id = auth.uid()
));

drop policy if exists "NORA action questions admin only" on public.nora_action_questions;
create policy "NORA action questions admin only" on public.nora_action_questions
for all to authenticated
using (public.is_admin() and exists (
  select 1 from public.nora_action_sessions s where s.id = session_id and s.user_id = auth.uid()
))
with check (public.is_admin() and exists (
  select 1 from public.nora_action_sessions s where s.id = session_id and s.user_id = auth.uid()
));

-- Keep updated_at truthful for the session monitor.
create or replace function public.touch_nora_action_session_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists nora_action_sessions_touch_updated_at on public.nora_action_sessions;
create trigger nora_action_sessions_touch_updated_at
before update on public.nora_action_sessions
for each row execute function public.touch_nora_action_session_updated_at();

-- Realtime is best-effort because a table may already be present in the publication.
do $$
begin
  begin alter publication supabase_realtime add table public.nora_action_sessions; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.nora_action_steps; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.nora_action_questions; exception when duplicate_object then null; end;
end $$;
