/*
  # AI Insights System

  1. New Tables
    - `ai_insights`
      - Stores AI-generated insights and recommendations
      - Types: stock, sales, pricing, anomaly
      - Severity levels: low, medium, high, critical
      - Links to products/orders via reference_id
    
    - `ai_actions`
      - Stores suggested actions that can be approved
      - Tracks execution status
      - Links to insights that generated them
  
  2. Security
    - Enable RLS on both tables
    - Authenticated users can view insights
    - Only admins can execute actions
  
  3. Indexes
    - ai_insights(type, severity) for filtering
    - ai_insights(reference_id) for product/order lookup
    - ai_insights(created_at) for time-based queries
    - ai_actions(status) for pending actions
*/

-- Create AI insights table
CREATE TABLE IF NOT EXISTS ai_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL CHECK (type IN ('stock', 'sales', 'pricing', 'anomaly', 'trend')),
  severity text NOT NULL DEFAULT 'low' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  title text NOT NULL,
  message text NOT NULL,
  reference_id uuid,
  reference_type text CHECK (reference_type IN ('product', 'order', 'store', 'category')),
  data jsonb,
  is_dismissed boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create AI suggested actions table
CREATE TABLE IF NOT EXISTS ai_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  insight_id uuid REFERENCES ai_insights(id) ON DELETE CASCADE,
  action_type text NOT NULL CHECK (action_type IN ('price_increase', 'price_decrease', 'restock', 'discontinue', 'promote')),
  title text NOT NULL,
  description text NOT NULL,
  action_data jsonb NOT NULL,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'executed')),
  approved_by uuid REFERENCES auth.users(id),
  approved_at timestamptz,
  executed_at timestamptz,
  execution_result jsonb,
  created_at timestamptz DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_ai_insights_type_severity ON ai_insights(type, severity);
CREATE INDEX IF NOT EXISTS idx_ai_insights_reference ON ai_insights(reference_id);
CREATE INDEX IF NOT EXISTS idx_ai_insights_created_at ON ai_insights(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_insights_dismissed ON ai_insights(is_dismissed);
CREATE INDEX IF NOT EXISTS idx_ai_actions_status ON ai_actions(status);
CREATE INDEX IF NOT EXISTS idx_ai_actions_insight ON ai_actions(insight_id);

-- Enable RLS
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_actions ENABLE ROW LEVEL SECURITY;

-- RLS Policies for ai_insights
CREATE POLICY "Authenticated users can view insights"
  ON ai_insights FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Service can insert insights"
  ON ai_insights FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update insights"
  ON ai_insights FOR UPDATE
  TO authenticated
  USING (true);

-- RLS Policies for ai_actions
CREATE POLICY "Authenticated users can view actions"
  ON ai_actions FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Service can insert actions"
  ON ai_actions FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update actions"
  ON ai_actions FOR UPDATE
  TO authenticated
  USING (true);

-- Add helpful comments
COMMENT ON TABLE ai_insights IS 'AI-generated business insights and alerts based on inventory, sales, and pricing data.';
COMMENT ON TABLE ai_actions IS 'Suggested actions generated by AI that require admin approval before execution.';

COMMENT ON COLUMN ai_insights.type IS 'Category of insight: stock (inventory), sales (performance), pricing (optimization), anomaly (unusual patterns), trend (predictions)';
COMMENT ON COLUMN ai_insights.severity IS 'Priority level: low (informational), medium (attention needed), high (action required), critical (urgent)';
COMMENT ON COLUMN ai_insights.data IS 'Additional structured data related to the insight (metrics, thresholds, etc.)';
COMMENT ON COLUMN ai_actions.action_data IS 'Structured data defining what action to take (product_id, price_change, quantity, etc.)';
COMMENT ON COLUMN ai_actions.status IS 'Lifecycle: pending (awaiting approval), approved (ready to execute), rejected (declined), executed (completed)';
