import { createClient } from 'npm:@supabase/supabase-js@2'

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } })
const admin = () => createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, { auth: { persistSession: false } })
const clean = (v: unknown) => typeof v === 'string' ? v.trim() : v == null ? '' : String(v).trim()
const enc = new TextEncoder()
const b64 = (bytes: Uint8Array) => { let s=''; for (const b of bytes) s += String.fromCharCode(b); return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'') }
const unb64 = (value: string) => { const padded=value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4); return Uint8Array.from(atob(padded),c=>c.charCodeAt(0)) }
const b64json = (v: unknown) => b64(enc.encode(JSON.stringify(v)))
const pemBytes = (pem: string) => unb64(pem.replace(/-----BEGIN [^-]+-----/g,'').replace(/-----END [^-]+-----/g,'').replace(/\s+/g,''))
async function cryptoKey() {
  const secret=Deno.env.get('MARKETING_TOKEN_ENCRYPTION_KEY')?.trim()
  if (!secret) throw new Error('Publisher credential encryption key is not configured')
  const raw=unb64(secret); if (raw.length!==32) throw new Error('Publisher credential encryption key is invalid')
  return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt'])
}
async function encrypt(value:string){const key=await cryptoKey();const iv=crypto.getRandomValues(new Uint8Array(12));const c=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(value)));const out=new Uint8Array(iv.length+c.length);out.set(iv);out.set(c,iv.length);return `enc:v1:${b64(out)}`}
async function decrypt(value:string){if(!value?.startsWith('enc:v1:'))throw new Error('Stored credential has an unsupported encryption format');const raw=unb64(value.slice(7));const p=await crypto.subtle.decrypt({name:'AES-GCM',iv:raw.slice(0,12)},await cryptoKey(),raw.slice(12));return new TextDecoder().decode(p)}
async function requireAdmin(req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)throw new Error('Authorization required');const db=admin();const {data:auth,error}=await db.auth.getUser(token);if(error||!auth.user)throw new Error('Invalid session');const {data:profile}=await db.from('user_profiles').select('profile_role,is_active').eq('id',auth.user.id).maybeSingle();if(profile?.profile_role!=='admin'||profile?.is_active===false)throw new Error('Admin access required');return {db,user:auth.user}}
async function account(db:any,providerId:string){const {data,error}=await db.from('app_publisher_accounts').select('*').eq('provider_id',providerId).eq('account_key','business_apps').maybeSingle();if(error)throw error;if(!data)throw new Error('Shared business publisher account is not configured');return data}
async function linkedApps(db:any,accountId:string){const {data,error}=await db.from('app_publisher_account_links').select('enabled,app:app_marketing_apps(id,store_id,platform,package_identifier,display_name,external_app_id,status,metadata,store:stores(name,slug))').eq('publisher_account_id',accountId).eq('enabled',true);if(error)throw error;return (data||[]).map((x:any)=>Array.isArray(x.app)?x.app[0]:x.app).filter(Boolean)}
function safeAccount(a:any,apps:any[]){return {id:a.id,provider_id:a.provider_id,display_name:a.display_name,account_scope:a.account_scope,status:a.status,public_config:a.public_config||{},stored_secrets:Object.keys(a.encrypted_secrets||{}),last_test_at:a.last_test_at,last_test_status:a.last_test_status,last_test_error:a.last_test_error,linked_apps:apps.map((x:any)=>({id:x.id,name:x.display_name,platform:x.platform,identifier:x.package_identifier,external_app_id:x.external_app_id,status:x.status,store:x.store}))}}
async function googleToken(a:any){const raw=a?.encrypted_secrets?.service_account_json;if(!raw)throw new Error('Google service account JSON is not stored');let service:any;try{service=JSON.parse(await decrypt(raw))}catch{throw new Error('Google service account JSON is invalid')}if(!service?.client_email||!service?.private_key)throw new Error('Google service account JSON must contain client_email and private_key');const now=Math.floor(Date.now()/1000);const header=b64json({alg:'RS256',typ:'JWT'});const claim=b64json({iss:service.client_email,scope:'https://www.googleapis.com/auth/androidpublisher',aud:service.token_uri||'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const input=`${header}.${claim}`;const key=await crypto.subtle.importKey('pkcs8',pemBytes(service.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc.encode(input)));const assertion=`${input}.${b64(sig)}`;const response=await fetch(service.token_uri||'https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});const body=await response.json().catch(()=>({}));if(!response.ok||!body?.access_token)throw new Error(body?.error_description||body?.error||`Google OAuth returned ${response.status}`);return String(body.access_token)}
async function appleToken(a:any){const issuer=clean(a?.public_config?.issuer_id),keyId=clean(a?.public_config?.key_id),raw=a?.encrypted_secrets?.private_key;if(!issuer||!keyId||!raw)throw new Error('Apple Issuer ID, Key ID and private key are required');const pem=await decrypt(raw);const now=Math.floor(Date.now()/1000);const header=b64json({alg:'ES256',kid:keyId,typ:'JWT'});const claim=b64json({iss:issuer,iat:now,exp:now+600,aud:'appstoreconnect-v1'});const input=`${header}.${claim}`;const key=await crypto.subtle.importKey('pkcs8',pemBytes(pem),{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,enc.encode(input)));if(sig.length!==64)throw new Error('Apple signing key returned an unexpected signature format');return `${input}.${b64(sig)}`}
async function save(db:any,providerId:string,values:any){const a=await account(db,providerId);const publicConfig={...(a.public_config||{})};const encryptedSecrets={...(a.encrypted_secrets||{})};if(providerId==='google_play'){const raw=clean(values?.service_account_json);if(raw){let parsed:any;try{parsed=JSON.parse(raw)}catch{throw new Error('Google Service Account JSON is not valid JSON')}if(!parsed?.client_email||!parsed?.private_key)throw new Error('Google Service Account JSON must contain client_email and private_key');encryptedSecrets.service_account_json=await encrypt(raw);publicConfig.service_account_email=parsed.client_email}else if(!encryptedSecrets.service_account_json)throw new Error('Google Service Account JSON is required')}else if(providerId==='app_store_connect'){const issuer=clean(values?.issuer_id)||clean(publicConfig.issuer_id);const keyId=clean(values?.key_id)||clean(publicConfig.key_id);const privateKey=clean(values?.private_key);if(!issuer||!keyId)throw new Error('Apple Issuer ID and Key ID are required');publicConfig.issuer_id=issuer;publicConfig.key_id=keyId;if(privateKey)encryptedSecrets.private_key=await encrypt(privateKey);else if(!encryptedSecrets.private_key)throw new Error('Apple private key is required')}else throw new Error('Unsupported publisher provider');const {data,error}=await db.from('app_publisher_accounts').update({status:'configured',public_config:publicConfig,encrypted_secrets:encryptedSecrets,last_test_at:null,last_test_status:null,last_test_error:null,updated_at:new Date().toISOString()}).eq('id',a.id).select('*').single();if(error)throw error;await db.rpc('sync_shared_publisher_account',{p_account_id:a.id});return data}
async function testGoogle(db:any,a:any,apps:any[]){const token=await googleToken(a);const candidates=[...apps].filter((x:any)=>x.platform==='android'&&x.status!=='needs_native_sync'&&x.metadata?.publishing_enabled!==false).sort((x:any,y:any)=>String(x.store?.slug)==='malluspices'?-1:String(y.store?.slug)==='malluspices'?1:0);if(!candidates.length)throw new Error('No publish-ready Android app is linked to the shared account');const failures:string[]=[];for(const app of candidates){const base=`https://androidpublisher.googleapis.com/androidpublisher/v3/applications/${encodeURIComponent(app.package_identifier)}/edits`;const r=await fetch(base,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'});const body=await r.json().catch(()=>({}));if(r.ok&&body?.id){await fetch(`${base}/${encodeURIComponent(body.id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}}).catch(()=>undefined);return {detail:`Google Play publisher verified using ${app.display_name||app.package_identifier}`,verified_app_id:app.id,verified_identifier:app.package_identifier,warnings:failures}}failures.push(`${app.package_identifier}: ${body?.error?.message||r.status}`)}throw new Error(`Google Play credential authenticated but no linked app was accessible. ${failures.slice(0,3).join(' | ')}`)}
async function testApple(a:any){const token=await appleToken(a);const r=await fetch('https://api.appstoreconnect.apple.com/v1/apps?limit=1',{headers:{Authorization:`Bearer ${token}`}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.errors?.[0]?.detail||`App Store Connect API returned ${r.status}`);return {detail:'App Store Connect shared publisher credential verified'}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const {db}=await requireAdmin(req);const body=await req.json().catch(()=>({}));const action=clean(body?.action||'overview');const providerId=clean(body?.providerId);if(action==='overview'){const {data,error}=await db.from('app_publisher_accounts').select('*').eq('account_key','business_apps').order('provider_id');if(error)throw error;const items=[];for(const a of data||[])items.push(safeAccount(a,await linkedApps(db,a.id)));return json({success:true,accounts:items})}if(!['google_play','app_store_connect'].includes(providerId))return json({success:false,error:'providerId must be google_play or app_store_connect'},400);if(action==='save'){const updated=await save(db,providerId,body?.values||{});return json({success:true,account:safeAccount(updated,await linkedApps(db,updated.id))})}if(action==='test'){const a=await account(db,providerId);const apps=await linkedApps(db,a.id);let result:any;try{result=providerId==='google_play'?await testGoogle(db,a,apps):await testApple(a);const now=new Date().toISOString();const {data,error}=await db.from('app_publisher_accounts').update({status:'configured',last_test_at:now,last_test_status:'passed',last_test_error:null,updated_at:now,metadata:{...(a.metadata||{}),last_verified_app_id:result.verified_app_id||null,last_verified_identifier:result.verified_identifier||null}}).eq('id',a.id).select('*').single();if(error)throw error;await db.rpc('sync_shared_publisher_account',{p_account_id:a.id});return json({success:true,result,account:safeAccount(data,apps)})}catch(e:any){const now=new Date().toISOString();await db.from('app_publisher_accounts').update({last_test_at:now,last_test_status:'failed',last_test_error:e?.message||'Publisher test failed',updated_at:now}).eq('id',a.id);await db.rpc('sync_shared_publisher_account',{p_account_id:a.id});throw e}}return json({success:false,error:'unsupported_action'},400)}catch(e:any){const message=e?.message||'Shared publisher operation failed';return json({success:false,error:message},/Authorization|session|Admin access/i.test(message)?401:400)}})
